<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询模板列表接口
Route::post('template/query', [\App\Bundles\Template\Controllers\TemplateController::class, 'query']);
// 新增模板接口
Route::post('template/store', [\App\Bundles\Template\Controllers\TemplateController::class, 'store']);
// 获取模板详情接口
Route::get('template/show', [\App\Bundles\Template\Controllers\TemplateController::class, 'show'])->name('template.show');
// 更新模板接口
Route::put('template/update', [\App\Bundles\Template\Controllers\TemplateController::class, 'update']);
// 删除模板接口
Route::delete('template/destroy', [\App\Bundles\Template\Controllers\TemplateController::class, 'destroy']);
