<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询用户账户列表接口
Route::post('userAccount/query', [\App\Bundles\User\Controllers\UserAccountController::class, 'query']);
// 新增用户账户接口
Route::post('userAccount/store', [\App\Bundles\User\Controllers\UserAccountController::class, 'store']);
// 获取用户账户详情接口
Route::get('userAccount/show', [\App\Bundles\User\Controllers\UserAccountController::class, 'show'])->name('userAccount.show');
// 更新用户账户接口
Route::put('userAccount/update', [\App\Bundles\User\Controllers\UserAccountController::class, 'update']);
// 删除用户账户接口
Route::delete('userAccount/destroy', [\App\Bundles\User\Controllers\UserAccountController::class, 'destroy']);
// 查询用户账户日志列表接口
Route::post('userAccountLog/query', [\App\Bundles\User\Controllers\UserAccountLogController::class, 'query']);
// 新增用户账户日志接口
Route::post('userAccountLog/store', [\App\Bundles\User\Controllers\UserAccountLogController::class, 'store']);
// 获取用户账户日志详情接口
Route::get('userAccountLog/show', [\App\Bundles\User\Controllers\UserAccountLogController::class, 'show'])->name('userAccountLog.show');
// 更新用户账户日志接口
Route::put('userAccountLog/update', [\App\Bundles\User\Controllers\UserAccountLogController::class, 'update']);
// 删除用户账户日志接口
Route::delete('userAccountLog/destroy', [\App\Bundles\User\Controllers\UserAccountLogController::class, 'destroy']);
// 查询用户地址列表接口
Route::post('userAddress/query', [\App\Bundles\User\Controllers\UserAddressController::class, 'query']);
// 新增用户地址接口
Route::post('userAddress/store', [\App\Bundles\User\Controllers\UserAddressController::class, 'store']);
// 获取用户地址详情接口
Route::get('userAddress/show', [\App\Bundles\User\Controllers\UserAddressController::class, 'show'])->name('userAddress.show');
// 更新用户地址接口
Route::put('userAddress/update', [\App\Bundles\User\Controllers\UserAddressController::class, 'update']);
// 删除用户地址接口
Route::delete('userAddress/destroy', [\App\Bundles\User\Controllers\UserAddressController::class, 'destroy']);
// 查询用户推荐关系列表接口
Route::post('userAffiliate/query', [\App\Bundles\User\Controllers\UserAffiliateController::class, 'query']);
// 新增用户推荐关系接口
Route::post('userAffiliate/store', [\App\Bundles\User\Controllers\UserAffiliateController::class, 'store']);
// 获取用户推荐关系详情接口
Route::get('userAffiliate/show', [\App\Bundles\User\Controllers\UserAffiliateController::class, 'show'])->name('userAffiliate.show');
// 更新用户推荐关系接口
Route::put('userAffiliate/update', [\App\Bundles\User\Controllers\UserAffiliateController::class, 'update']);
// 删除用户推荐关系接口
Route::delete('userAffiliate/destroy', [\App\Bundles\User\Controllers\UserAffiliateController::class, 'destroy']);
// 查询用户红包列表接口
Route::post('userBonus/query', [\App\Bundles\User\Controllers\UserBonusController::class, 'query']);
// 新增用户红包接口
Route::post('userBonus/store', [\App\Bundles\User\Controllers\UserBonusController::class, 'store']);
// 获取用户红包详情接口
Route::get('userBonus/show', [\App\Bundles\User\Controllers\UserBonusController::class, 'show'])->name('userBonus.show');
// 更新用户红包接口
Route::put('userBonus/update', [\App\Bundles\User\Controllers\UserBonusController::class, 'update']);
// 删除用户红包接口
Route::delete('userBonus/destroy', [\App\Bundles\User\Controllers\UserBonusController::class, 'destroy']);
// 查询用户缺货登记列表接口
Route::post('userBooking/query', [\App\Bundles\User\Controllers\UserBookingController::class, 'query']);
// 新增用户缺货登记接口
Route::post('userBooking/store', [\App\Bundles\User\Controllers\UserBookingController::class, 'store']);
// 获取用户缺货登记详情接口
Route::get('userBooking/show', [\App\Bundles\User\Controllers\UserBookingController::class, 'show'])->name('userBooking.show');
// 更新用户缺货登记接口
Route::put('userBooking/update', [\App\Bundles\User\Controllers\UserBookingController::class, 'update']);
// 删除用户缺货登记接口
Route::delete('userBooking/destroy', [\App\Bundles\User\Controllers\UserBookingController::class, 'destroy']);
// 查询购物车列表接口
Route::post('userCart/query', [\App\Bundles\User\Controllers\UserCartController::class, 'query']);
// 新增购物车接口
Route::post('userCart/store', [\App\Bundles\User\Controllers\UserCartController::class, 'store']);
// 获取购物车详情接口
Route::get('userCart/show', [\App\Bundles\User\Controllers\UserCartController::class, 'show'])->name('userCart.show');
// 更新购物车接口
Route::put('userCart/update', [\App\Bundles\User\Controllers\UserCartController::class, 'update']);
// 删除购物车接口
Route::delete('userCart/destroy', [\App\Bundles\User\Controllers\UserCartController::class, 'destroy']);
// 查询用户收藏列表接口
Route::post('userCollect/query', [\App\Bundles\User\Controllers\UserCollectController::class, 'query']);
// 新增用户收藏接口
Route::post('userCollect/store', [\App\Bundles\User\Controllers\UserCollectController::class, 'store']);
// 获取用户收藏详情接口
Route::get('userCollect/show', [\App\Bundles\User\Controllers\UserCollectController::class, 'show'])->name('userCollect.show');
// 更新用户收藏接口
Route::put('userCollect/update', [\App\Bundles\User\Controllers\UserCollectController::class, 'update']);
// 删除用户收藏接口
Route::delete('userCollect/destroy', [\App\Bundles\User\Controllers\UserCollectController::class, 'destroy']);
// 查询用户列表接口
Route::post('user/query', [\App\Bundles\User\Controllers\UserController::class, 'query']);
// 新增用户接口
Route::post('user/store', [\App\Bundles\User\Controllers\UserController::class, 'store']);
// 获取用户详情接口
Route::get('user/show', [\App\Bundles\User\Controllers\UserController::class, 'show'])->name('user.show');
// 更新用户接口
Route::put('user/update', [\App\Bundles\User\Controllers\UserController::class, 'update']);
// 删除用户接口
Route::delete('user/destroy', [\App\Bundles\User\Controllers\UserController::class, 'destroy']);
// 查询用户扩展字段列表接口
Route::post('userExtendFields/query', [\App\Bundles\User\Controllers\UserExtendFieldsController::class, 'query']);
// 新增用户扩展字段接口
Route::post('userExtendFields/store', [\App\Bundles\User\Controllers\UserExtendFieldsController::class, 'store']);
// 获取用户扩展字段详情接口
Route::get('userExtendFields/show', [\App\Bundles\User\Controllers\UserExtendFieldsController::class, 'show'])->name('userExtendFields.show');
// 更新用户扩展字段接口
Route::put('userExtendFields/update', [\App\Bundles\User\Controllers\UserExtendFieldsController::class, 'update']);
// 删除用户扩展字段接口
Route::delete('userExtendFields/destroy', [\App\Bundles\User\Controllers\UserExtendFieldsController::class, 'destroy']);
// 查询用户扩展信息列表接口
Route::post('userExtendInfo/query', [\App\Bundles\User\Controllers\UserExtendInfoController::class, 'query']);
// 新增用户扩展信息接口
Route::post('userExtendInfo/store', [\App\Bundles\User\Controllers\UserExtendInfoController::class, 'store']);
// 获取用户扩展信息详情接口
Route::get('userExtendInfo/show', [\App\Bundles\User\Controllers\UserExtendInfoController::class, 'show'])->name('userExtendInfo.show');
// 更新用户扩展信息接口
Route::put('userExtendInfo/update', [\App\Bundles\User\Controllers\UserExtendInfoController::class, 'update']);
// 删除用户扩展信息接口
Route::delete('userExtendInfo/destroy', [\App\Bundles\User\Controllers\UserExtendInfoController::class, 'destroy']);
// 查询用户反馈列表接口
Route::post('userFeed/query', [\App\Bundles\User\Controllers\UserFeedController::class, 'query']);
// 新增用户反馈接口
Route::post('userFeed/store', [\App\Bundles\User\Controllers\UserFeedController::class, 'store']);
// 获取用户反馈详情接口
Route::get('userFeed/show', [\App\Bundles\User\Controllers\UserFeedController::class, 'show'])->name('userFeed.show');
// 更新用户反馈接口
Route::put('userFeed/update', [\App\Bundles\User\Controllers\UserFeedController::class, 'update']);
// 删除用户反馈接口
Route::delete('userFeed/destroy', [\App\Bundles\User\Controllers\UserFeedController::class, 'destroy']);
// 查询用户等级列表接口
Route::post('userRank/query', [\App\Bundles\User\Controllers\UserRankController::class, 'query']);
// 新增用户等级接口
Route::post('userRank/store', [\App\Bundles\User\Controllers\UserRankController::class, 'store']);
// 获取用户等级详情接口
Route::get('userRank/show', [\App\Bundles\User\Controllers\UserRankController::class, 'show'])->name('userRank.show');
// 更新用户等级接口
Route::put('userRank/update', [\App\Bundles\User\Controllers\UserRankController::class, 'update']);
// 删除用户等级接口
Route::delete('userRank/destroy', [\App\Bundles\User\Controllers\UserRankController::class, 'destroy']);
// 查询用户标签列表接口
Route::post('userTag/query', [\App\Bundles\User\Controllers\UserTagController::class, 'query']);
// 新增用户标签接口
Route::post('userTag/store', [\App\Bundles\User\Controllers\UserTagController::class, 'store']);
// 获取用户标签详情接口
Route::get('userTag/show', [\App\Bundles\User\Controllers\UserTagController::class, 'show'])->name('userTag.show');
// 更新用户标签接口
Route::put('userTag/update', [\App\Bundles\User\Controllers\UserTagController::class, 'update']);
// 删除用户标签接口
Route::delete('userTag/destroy', [\App\Bundles\User\Controllers\UserTagController::class, 'destroy']);
