<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询投票列表接口
Route::post('vote/query', [\App\Bundles\Vote\Controllers\VoteController::class, 'query']);
// 新增投票接口
Route::post('vote/store', [\App\Bundles\Vote\Controllers\VoteController::class, 'store']);
// 获取投票详情接口
Route::get('vote/show', [\App\Bundles\Vote\Controllers\VoteController::class, 'show'])->name('vote.show');
// 更新投票接口
Route::put('vote/update', [\App\Bundles\Vote\Controllers\VoteController::class, 'update']);
// 删除投票接口
Route::delete('vote/destroy', [\App\Bundles\Vote\Controllers\VoteController::class, 'destroy']);
// 查询投票记录列表接口
Route::post('voteLog/query', [\App\Bundles\Vote\Controllers\VoteLogController::class, 'query']);
// 新增投票记录接口
Route::post('voteLog/store', [\App\Bundles\Vote\Controllers\VoteLogController::class, 'store']);
// 获取投票记录详情接口
Route::get('voteLog/show', [\App\Bundles\Vote\Controllers\VoteLogController::class, 'show'])->name('voteLog.show');
// 更新投票记录接口
Route::put('voteLog/update', [\App\Bundles\Vote\Controllers\VoteLogController::class, 'update']);
// 删除投票记录接口
Route::delete('voteLog/destroy', [\App\Bundles\Vote\Controllers\VoteLogController::class, 'destroy']);
// 查询投票选项列表接口
Route::post('voteOption/query', [\App\Bundles\Vote\Controllers\VoteOptionController::class, 'query']);
// 新增投票选项接口
Route::post('voteOption/store', [\App\Bundles\Vote\Controllers\VoteOptionController::class, 'store']);
// 获取投票选项详情接口
Route::get('voteOption/show', [\App\Bundles\Vote\Controllers\VoteOptionController::class, 'show'])->name('voteOption.show');
// 更新投票选项接口
Route::put('voteOption/update', [\App\Bundles\Vote\Controllers\VoteOptionController::class, 'update']);
// 删除投票选项接口
Route::delete('voteOption/destroy', [\App\Bundles\Vote\Controllers\VoteOptionController::class, 'destroy']);
