<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('api/seller')->middleware('api')->group(function () {
    // 卖家
    Route::get('dashboard', [\App\API\Merchant\Controllers\IndexController::class, 'dashboard']);
});
// end
