<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询支付方式列表接口
Route::post('payment/query', [\App\Bundles\Payment\Controllers\PaymentController::class, 'query']);
// 新增支付方式接口
Route::post('payment/store', [\App\Bundles\Payment\Controllers\PaymentController::class, 'store']);
// 获取支付方式详情接口
Route::get('payment/show', [\App\Bundles\Payment\Controllers\PaymentController::class, 'show'])->name('payment.show');
// 更新支付方式接口
Route::put('payment/update', [\App\Bundles\Payment\Controllers\PaymentController::class, 'update']);
// 删除支付方式接口
Route::delete('payment/destroy', [\App\Bundles\Payment\Controllers\PaymentController::class, 'destroy']);
