<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询广告联盟列表接口
Route::post('adAdsense/query', [\App\Bundles\Ad\Controllers\AdAdsenseController::class, 'query']);
// 新增广告联盟接口
Route::post('adAdsense/store', [\App\Bundles\Ad\Controllers\AdAdsenseController::class, 'store']);
// 获取广告联盟详情接口
Route::get('adAdsense/show', [\App\Bundles\Ad\Controllers\AdAdsenseController::class, 'show'])->name('adAdsense.show');
// 更新广告联盟接口
Route::put('adAdsense/update', [\App\Bundles\Ad\Controllers\AdAdsenseController::class, 'update']);
// 删除广告联盟接口
Route::delete('adAdsense/destroy', [\App\Bundles\Ad\Controllers\AdAdsenseController::class, 'destroy']);
// 查询广告列表接口
Route::post('ad/query', [\App\Bundles\Ad\Controllers\AdController::class, 'query']);
// 新增广告接口
Route::post('ad/store', [\App\Bundles\Ad\Controllers\AdController::class, 'store']);
// 获取广告详情接口
Route::get('ad/show', [\App\Bundles\Ad\Controllers\AdController::class, 'show'])->name('ad.show');
// 更新广告接口
Route::put('ad/update', [\App\Bundles\Ad\Controllers\AdController::class, 'update']);
// 删除广告接口
Route::delete('ad/destroy', [\App\Bundles\Ad\Controllers\AdController::class, 'destroy']);
// 查询自定义广告列表接口
Route::post('adCustom/query', [\App\Bundles\Ad\Controllers\AdCustomController::class, 'query']);
// 新增自定义广告接口
Route::post('adCustom/store', [\App\Bundles\Ad\Controllers\AdCustomController::class, 'store']);
// 获取自定义广告详情接口
Route::get('adCustom/show', [\App\Bundles\Ad\Controllers\AdCustomController::class, 'show'])->name('adCustom.show');
// 更新自定义广告接口
Route::put('adCustom/update', [\App\Bundles\Ad\Controllers\AdCustomController::class, 'update']);
// 删除自定义广告接口
Route::delete('adCustom/destroy', [\App\Bundles\Ad\Controllers\AdCustomController::class, 'destroy']);
// 查询广告位置列表接口
Route::post('adPosition/query', [\App\Bundles\Ad\Controllers\AdPositionController::class, 'query']);
// 新增广告位置接口
Route::post('adPosition/store', [\App\Bundles\Ad\Controllers\AdPositionController::class, 'store']);
// 获取广告位置详情接口
Route::get('adPosition/show', [\App\Bundles\Ad\Controllers\AdPositionController::class, 'show'])->name('adPosition.show');
// 更新广告位置接口
Route::put('adPosition/update', [\App\Bundles\Ad\Controllers\AdPositionController::class, 'update']);
// 删除广告位置接口
Route::delete('adPosition/destroy', [\App\Bundles\Ad\Controllers\AdPositionController::class, 'destroy']);
