<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询配送区域列表接口
Route::post('shippingArea/query', [\App\Bundles\Shipping\Controllers\ShippingAreaController::class, 'query']);
// 新增配送区域接口
Route::post('shippingArea/store', [\App\Bundles\Shipping\Controllers\ShippingAreaController::class, 'store']);
// 获取配送区域详情接口
Route::get('shippingArea/show', [\App\Bundles\Shipping\Controllers\ShippingAreaController::class, 'show'])->name('shippingArea.show');
// 更新配送区域接口
Route::put('shippingArea/update', [\App\Bundles\Shipping\Controllers\ShippingAreaController::class, 'update']);
// 删除配送区域接口
Route::delete('shippingArea/destroy', [\App\Bundles\Shipping\Controllers\ShippingAreaController::class, 'destroy']);
// 查询配送区域地区列表接口
Route::post('shippingAreaRegion/query', [\App\Bundles\Shipping\Controllers\ShippingAreaRegionController::class, 'query']);
// 新增配送区域地区接口
Route::post('shippingAreaRegion/store', [\App\Bundles\Shipping\Controllers\ShippingAreaRegionController::class, 'store']);
// 获取配送区域地区详情接口
Route::get('shippingAreaRegion/show', [\App\Bundles\Shipping\Controllers\ShippingAreaRegionController::class, 'show'])->name('shippingAreaRegion.show');
// 更新配送区域地区接口
Route::put('shippingAreaRegion/update', [\App\Bundles\Shipping\Controllers\ShippingAreaRegionController::class, 'update']);
// 删除配送区域地区接口
Route::delete('shippingAreaRegion/destroy', [\App\Bundles\Shipping\Controllers\ShippingAreaRegionController::class, 'destroy']);
// 查询配送方式列表接口
Route::post('shipping/query', [\App\Bundles\Shipping\Controllers\ShippingController::class, 'query']);
// 新增配送方式接口
Route::post('shipping/store', [\App\Bundles\Shipping\Controllers\ShippingController::class, 'store']);
// 获取配送方式详情接口
Route::get('shipping/show', [\App\Bundles\Shipping\Controllers\ShippingController::class, 'show'])->name('shipping.show');
// 更新配送方式接口
Route::put('shipping/update', [\App\Bundles\Shipping\Controllers\ShippingController::class, 'update']);
// 删除配送方式接口
Route::delete('shipping/destroy', [\App\Bundles\Shipping\Controllers\ShippingController::class, 'destroy']);
