packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
  antd: ^6.4.5
  '@ant-design/icons': ^6.2.5
  '@ant-design/pro-components': ^2.8.10
  react-router-dom: ^7.18.0
  '@tanstack/react-query': ^5.101.1
  zustand: ^5.0.14
  axios: ^1.18.1
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  core-js: true
  esbuild: false
  sharp: false
