<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('api/admin')->middleware('api')->group(function () {
    // 买家收货地址
    Route::get('address', [\App\Bundles\UMS\Controllers\Admin\AddressController::class, 'index']);
    // 广告列表
    Route::get('ad', [\App\Bundles\CMS\Migrations\Advertising\Controllers\Admin\AdController::class, 'index']);
    // 广告位列表
    Route::get('adPosition', [\App\Bundles\CMS\Migrations\Advertising\Controllers\Admin\AdPositionController::class, 'index']);
    // 评论列表
    Route::get('comment', [\App\Bundles\CMS\Migrations\Comment\Controllers\Admin\IndexController::class, 'index']);
    // 栏目列表
    Route::get('category', [\App\Bundles\CMS\Migrations\Content\Controllers\Admin\CategoryController::class, 'index']);
    // 内容列表
    Route::get('content', [\App\Bundles\CMS\Migrations\Content\Controllers\Admin\ContentController::class, 'index']);
    // 表单列表
    Route::get('form', [\App\Bundles\CMS\Migrations\Content\Controllers\Admin\FormController::class, 'index']);
    // 模型列表
    Route::get('pattern', [\App\Bundles\CMS\Migrations\Content\Controllers\Admin\PatternController::class, 'index']);
    // 标签列表
    Route::get('segment', [\App\Bundles\CMS\Migrations\Content\Controllers\Admin\SegmentController::class, 'index']);
    // 数据库管理
    Route::get('database', [\App\Foundation\Infra\Database\Controllers\Admin\DatabaseController::class, 'index']);
    // 通过用户名和密码登录
    Route::post('login', [\App\Bundles\Auth\Controllers\Admin\LoginController::class, 'index']);
    // 通过手机号和密码登录
    Route::post('login/mobile', [\App\Bundles\Auth\Controllers\Admin\LoginController::class, 'mobile']);
    // 运营首页
    Route::get('dashboard', [\App\Bundles\System\Controllers\Admin\DashboardController::class, 'index']);
    // 管理员信息
    Route::get('profile', [\App\Bundles\System\Controllers\Admin\IndexController::class, 'profile']);
    // 管理菜单
    Route::get('menu', [\App\Bundles\System\Controllers\Admin\IndexController::class, 'menu']);
    // 系统消息
    Route::get('message', [\App\Bundles\System\Controllers\Admin\IndexController::class, 'message']);
    // 修改密码
    Route::post('password', [\App\Bundles\System\Controllers\Admin\IndexController::class, 'password']);
    // 注销登录
    Route::post('logout', [\App\Bundles\System\Controllers\Admin\IndexController::class, 'logout']);
    // 权限列表
    Route::get('permission', [\App\Bundles\System\Controllers\Admin\PermissionController::class, 'index']);
    // 角色列表
    Route::get('role', [\App\Bundles\System\Controllers\Admin\RoleController::class, 'index']);
    // 管理员接口
    Route::get('admin', [\App\Bundles\UMS\Controllers\Admin\AdminController::class, 'index']);
    // 用户列表
    Route::get('user', [\App\Bundles\UMS\Controllers\Admin\UserController::class, 'index']);
    // 添加新用户
    Route::post('user/store', [\App\Bundles\UMS\Controllers\Admin\UserController::class, 'store']);
    // 获取详情
    Route::get('user/show', [\App\Bundles\UMS\Controllers\Admin\UserController::class, 'show']);
    // 更新用户详情
    Route::put('user/update', [\App\Bundles\UMS\Controllers\Admin\UserController::class, 'update']);
    // 删除用户
    Route::delete('user/destroy', [\App\Bundles\UMS\Controllers\Admin\UserController::class, 'destroy']);
});
// end
