<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询商品活动关联列表接口
Route::post('goodsActivity/query', [\App\Bundles\Goods\Controllers\GoodsActivityController::class, 'query']);
// 新增商品活动关联接口
Route::post('goodsActivity/store', [\App\Bundles\Goods\Controllers\GoodsActivityController::class, 'store']);
// 获取商品活动关联详情接口
Route::get('goodsActivity/show', [\App\Bundles\Goods\Controllers\GoodsActivityController::class, 'show'])->name('goodsActivity.show');
// 更新商品活动关联接口
Route::put('goodsActivity/update', [\App\Bundles\Goods\Controllers\GoodsActivityController::class, 'update']);
// 删除商品活动关联接口
Route::delete('goodsActivity/destroy', [\App\Bundles\Goods\Controllers\GoodsActivityController::class, 'destroy']);
// 查询商品文章关联列表接口
Route::post('goodsArticle/query', [\App\Bundles\Goods\Controllers\GoodsArticleController::class, 'query']);
// 新增商品文章关联接口
Route::post('goodsArticle/store', [\App\Bundles\Goods\Controllers\GoodsArticleController::class, 'store']);
// 获取商品文章关联详情接口
Route::get('goodsArticle/show', [\App\Bundles\Goods\Controllers\GoodsArticleController::class, 'show'])->name('goodsArticle.show');
// 更新商品文章关联接口
Route::put('goodsArticle/update', [\App\Bundles\Goods\Controllers\GoodsArticleController::class, 'update']);
// 删除商品文章关联接口
Route::delete('goodsArticle/destroy', [\App\Bundles\Goods\Controllers\GoodsArticleController::class, 'destroy']);
// 查询商品属性列表接口
Route::post('goodsAttr/query', [\App\Bundles\Goods\Controllers\GoodsAttrController::class, 'query']);
// 新增商品属性接口
Route::post('goodsAttr/store', [\App\Bundles\Goods\Controllers\GoodsAttrController::class, 'store']);
// 获取商品属性详情接口
Route::get('goodsAttr/show', [\App\Bundles\Goods\Controllers\GoodsAttrController::class, 'show'])->name('goodsAttr.show');
// 更新商品属性接口
Route::put('goodsAttr/update', [\App\Bundles\Goods\Controllers\GoodsAttrController::class, 'update']);
// 删除商品属性接口
Route::delete('goodsAttr/destroy', [\App\Bundles\Goods\Controllers\GoodsAttrController::class, 'destroy']);
// 查询商品品牌列表接口
Route::post('goodsBrand/query', [\App\Bundles\Goods\Controllers\GoodsBrandController::class, 'query']);
// 新增商品品牌接口
Route::post('goodsBrand/store', [\App\Bundles\Goods\Controllers\GoodsBrandController::class, 'store']);
// 获取商品品牌详情接口
Route::get('goodsBrand/show', [\App\Bundles\Goods\Controllers\GoodsBrandController::class, 'show'])->name('goodsBrand.show');
// 更新商品品牌接口
Route::put('goodsBrand/update', [\App\Bundles\Goods\Controllers\GoodsBrandController::class, 'update']);
// 删除商品品牌接口
Route::delete('goodsBrand/destroy', [\App\Bundles\Goods\Controllers\GoodsBrandController::class, 'destroy']);
// 查询商品分类关联列表接口
Route::post('goodsCat/query', [\App\Bundles\Goods\Controllers\GoodsCatController::class, 'query']);
// 新增商品分类关联接口
Route::post('goodsCat/store', [\App\Bundles\Goods\Controllers\GoodsCatController::class, 'store']);
// 获取商品分类关联详情接口
Route::get('goodsCat/show', [\App\Bundles\Goods\Controllers\GoodsCatController::class, 'show'])->name('goodsCat.show');
// 更新商品分类关联接口
Route::put('goodsCat/update', [\App\Bundles\Goods\Controllers\GoodsCatController::class, 'update']);
// 删除商品分类关联接口
Route::delete('goodsCat/destroy', [\App\Bundles\Goods\Controllers\GoodsCatController::class, 'destroy']);
// 查询商品分类推荐列表接口
Route::post('goodsCatRecommend/query', [\App\Bundles\Goods\Controllers\GoodsCatRecommendController::class, 'query']);
// 新增商品分类推荐接口
Route::post('goodsCatRecommend/store', [\App\Bundles\Goods\Controllers\GoodsCatRecommendController::class, 'store']);
// 获取商品分类推荐详情接口
Route::get('goodsCatRecommend/show', [\App\Bundles\Goods\Controllers\GoodsCatRecommendController::class, 'show'])->name('goodsCatRecommend.show');
// 更新商品分类推荐接口
Route::put('goodsCatRecommend/update', [\App\Bundles\Goods\Controllers\GoodsCatRecommendController::class, 'update']);
// 删除商品分类推荐接口
Route::delete('goodsCatRecommend/destroy', [\App\Bundles\Goods\Controllers\GoodsCatRecommendController::class, 'destroy']);
// 查询商品分类列表接口
Route::post('goodsCategory/query', [\App\Bundles\Goods\Controllers\GoodsCategoryController::class, 'query']);
// 新增商品分类接口
Route::post('goodsCategory/store', [\App\Bundles\Goods\Controllers\GoodsCategoryController::class, 'store']);
// 获取商品分类详情接口
Route::get('goodsCategory/show', [\App\Bundles\Goods\Controllers\GoodsCategoryController::class, 'show'])->name('goodsCategory.show');
// 更新商品分类接口
Route::put('goodsCategory/update', [\App\Bundles\Goods\Controllers\GoodsCategoryController::class, 'update']);
// 删除商品分类接口
Route::delete('goodsCategory/destroy', [\App\Bundles\Goods\Controllers\GoodsCategoryController::class, 'destroy']);
// 查询商品列表接口
Route::post('goods/query', [\App\Bundles\Goods\Controllers\GoodsController::class, 'query']);
// 新增商品接口
Route::post('goods/store', [\App\Bundles\Goods\Controllers\GoodsController::class, 'store']);
// 获取商品详情接口
Route::get('goods/show', [\App\Bundles\Goods\Controllers\GoodsController::class, 'show'])->name('goods.show');
// 更新商品接口
Route::put('goods/update', [\App\Bundles\Goods\Controllers\GoodsController::class, 'update']);
// 删除商品接口
Route::delete('goods/destroy', [\App\Bundles\Goods\Controllers\GoodsController::class, 'destroy']);
// 查询商品相册列表接口
Route::post('goodsGallery/query', [\App\Bundles\Goods\Controllers\GoodsGalleryController::class, 'query']);
// 新增商品相册接口
Route::post('goodsGallery/store', [\App\Bundles\Goods\Controllers\GoodsGalleryController::class, 'store']);
// 获取商品相册详情接口
Route::get('goodsGallery/show', [\App\Bundles\Goods\Controllers\GoodsGalleryController::class, 'show'])->name('goodsGallery.show');
// 更新商品相册接口
Route::put('goodsGallery/update', [\App\Bundles\Goods\Controllers\GoodsGalleryController::class, 'update']);
// 删除商品相册接口
Route::delete('goodsGallery/destroy', [\App\Bundles\Goods\Controllers\GoodsGalleryController::class, 'destroy']);
// 查询关联商品列表接口
Route::post('goodsLinkGoods/query', [\App\Bundles\Goods\Controllers\GoodsLinkGoodsController::class, 'query']);
// 新增关联商品接口
Route::post('goodsLinkGoods/store', [\App\Bundles\Goods\Controllers\GoodsLinkGoodsController::class, 'store']);
// 获取关联商品详情接口
Route::get('goodsLinkGoods/show', [\App\Bundles\Goods\Controllers\GoodsLinkGoodsController::class, 'show'])->name('goodsLinkGoods.show');
// 更新关联商品接口
Route::put('goodsLinkGoods/update', [\App\Bundles\Goods\Controllers\GoodsLinkGoodsController::class, 'update']);
// 删除关联商品接口
Route::delete('goodsLinkGoods/destroy', [\App\Bundles\Goods\Controllers\GoodsLinkGoodsController::class, 'destroy']);
// 查询商品会员价格列表接口
Route::post('goodsMemberPrice/query', [\App\Bundles\Goods\Controllers\GoodsMemberPriceController::class, 'query']);
// 新增商品会员价格接口
Route::post('goodsMemberPrice/store', [\App\Bundles\Goods\Controllers\GoodsMemberPriceController::class, 'store']);
// 获取商品会员价格详情接口
Route::get('goodsMemberPrice/show', [\App\Bundles\Goods\Controllers\GoodsMemberPriceController::class, 'show'])->name('goodsMemberPrice.show');
// 更新商品会员价格接口
Route::put('goodsMemberPrice/update', [\App\Bundles\Goods\Controllers\GoodsMemberPriceController::class, 'update']);
// 删除商品会员价格接口
Route::delete('goodsMemberPrice/destroy', [\App\Bundles\Goods\Controllers\GoodsMemberPriceController::class, 'destroy']);
// 查询商品货品列表接口
Route::post('goodsProduct/query', [\App\Bundles\Goods\Controllers\GoodsProductController::class, 'query']);
// 新增商品货品接口
Route::post('goodsProduct/store', [\App\Bundles\Goods\Controllers\GoodsProductController::class, 'store']);
// 获取商品货品详情接口
Route::get('goodsProduct/show', [\App\Bundles\Goods\Controllers\GoodsProductController::class, 'show'])->name('goodsProduct.show');
// 更新商品货品接口
Route::put('goodsProduct/update', [\App\Bundles\Goods\Controllers\GoodsProductController::class, 'update']);
// 删除商品货品接口
Route::delete('goodsProduct/destroy', [\App\Bundles\Goods\Controllers\GoodsProductController::class, 'destroy']);
// 查询商品类型属性列表接口
Route::post('goodsTypeAttribute/query', [\App\Bundles\Goods\Controllers\GoodsTypeAttributeController::class, 'query']);
// 新增商品类型属性接口
Route::post('goodsTypeAttribute/store', [\App\Bundles\Goods\Controllers\GoodsTypeAttributeController::class, 'store']);
// 获取商品类型属性详情接口
Route::get('goodsTypeAttribute/show', [\App\Bundles\Goods\Controllers\GoodsTypeAttributeController::class, 'show'])->name('goodsTypeAttribute.show');
// 更新商品类型属性接口
Route::put('goodsTypeAttribute/update', [\App\Bundles\Goods\Controllers\GoodsTypeAttributeController::class, 'update']);
// 删除商品类型属性接口
Route::delete('goodsTypeAttribute/destroy', [\App\Bundles\Goods\Controllers\GoodsTypeAttributeController::class, 'destroy']);
// 查询商品类型列表接口
Route::post('goodsType/query', [\App\Bundles\Goods\Controllers\GoodsTypeController::class, 'query']);
// 新增商品类型接口
Route::post('goodsType/store', [\App\Bundles\Goods\Controllers\GoodsTypeController::class, 'store']);
// 获取商品类型详情接口
Route::get('goodsType/show', [\App\Bundles\Goods\Controllers\GoodsTypeController::class, 'show'])->name('goodsType.show');
// 更新商品类型接口
Route::put('goodsType/update', [\App\Bundles\Goods\Controllers\GoodsTypeController::class, 'update']);
// 删除商品类型接口
Route::delete('goodsType/destroy', [\App\Bundles\Goods\Controllers\GoodsTypeController::class, 'destroy']);
// 查询虚拟商品卡密列表接口
Route::post('goodsVirtualCard/query', [\App\Bundles\Goods\Controllers\GoodsVirtualCardController::class, 'query']);
// 新增虚拟商品卡密接口
Route::post('goodsVirtualCard/store', [\App\Bundles\Goods\Controllers\GoodsVirtualCardController::class, 'store']);
// 获取虚拟商品卡密详情接口
Route::get('goodsVirtualCard/show', [\App\Bundles\Goods\Controllers\GoodsVirtualCardController::class, 'show'])->name('goodsVirtualCard.show');
// 更新虚拟商品卡密接口
Route::put('goodsVirtualCard/update', [\App\Bundles\Goods\Controllers\GoodsVirtualCardController::class, 'update']);
// 删除虚拟商品卡密接口
Route::delete('goodsVirtualCard/destroy', [\App\Bundles\Goods\Controllers\GoodsVirtualCardController::class, 'destroy']);
// 查询商品批量价格列表接口
Route::post('goodsVolumePrice/query', [\App\Bundles\Goods\Controllers\GoodsVolumePriceController::class, 'query']);
// 新增商品批量价格接口
Route::post('goodsVolumePrice/store', [\App\Bundles\Goods\Controllers\GoodsVolumePriceController::class, 'store']);
// 获取商品批量价格详情接口
Route::get('goodsVolumePrice/show', [\App\Bundles\Goods\Controllers\GoodsVolumePriceController::class, 'show'])->name('goodsVolumePrice.show');
// 更新商品批量价格接口
Route::put('goodsVolumePrice/update', [\App\Bundles\Goods\Controllers\GoodsVolumePriceController::class, 'update']);
// 删除商品批量价格接口
Route::delete('goodsVolumePrice/destroy', [\App\Bundles\Goods\Controllers\GoodsVolumePriceController::class, 'destroy']);
