openapi: 3.0.0
info:
  title: API文档
  description: 运营平台接口
  contact:
    name: 'API Develop Team'
  version: '1.0'
servers:
  -
    url: 'http://127.0.0.1:8000/admin'
    description: 开发环境
  -
    url: 'https://demo.phpmall.net/admin'
    description: 测试环境
paths:
  /:
    get:
      tags:
        - 运营
      summary: 运营首页
      operationId: 85b4b3c8cb94c9886e4470ee6ad5f584
      responses:
        '200':
          description: OK
