openapi: 3.0.0
info:
  title: API文档
  description: 卖家平台接口
  contact:
    name: 'API Develop Team'
  version: '1.0'
servers:
  -
    url: 'http://127.0.0.1:8000/api/seller'
    description: 开发环境
  -
    url: 'https://demo.phpmall.net/api/seller'
    description: 测试环境
paths:
  /:
    get:
      tags:
        - seller
      summary: 卖家
      operationId: f7fc84819717cd793cc468d1491cdd4d
      responses:
        '200':
          description: OK
