<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 管理员登录接口
Route::post('auth/login', [\App\Api\Admin\Controllers\AuthController::class, 'login']);
