<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('api/common')->middleware('api')->group(function () {
    // 图片验证码
    Route::get('captcha', [\App\Bundles\Captcha\API\Common\Controllers\CaptchaController::class, 'index']);
    // 查询地区列表
    Route::get('region', [\App\Bundles\Region\API\Common\Controllers\RegionController::class, 'index']);
    // 发送手机短信验证码
    Route::post('sms', [\App\Bundles\Sms\API\Common\Controllers\SmsController::class, 'index']);
});
// end
