'use client'

import './globals.css'
import type { Metadata } from 'next'
import { ConfigProvider } from 'antd'
import zhCN from 'antd/locale/zh_CN'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-Hans">
      <body>
        <ConfigProvider theme={{
          token: {
            colorPrimary: '#00b96b',
          },
        }} locale={zhCN}>
          {children}
        </ConfigProvider>
      </body>
    </html>
  )
}
