<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Domains\Cart\Controllers\CartController;
use Illuminate\Support\Facades\Route;

// 查询购物车列表接口
Route::post('cart/search', [CartController::class, 'search']);
// 新增购物车接口
Route::post('cart/store', [CartController::class, 'store']);
// 获取购物车详情接口
Route::get('cart/show', [CartController::class, 'show'])->name('cart.show');
// 更新购物车接口
Route::put('cart/update', [CartController::class, 'update']);
// 删除购物车接口
Route::post('cart/destroy', [CartController::class, 'destroy']);
