<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 首页
Route::get('/', [\App\Api\Shop\Controllers\IndexController::class, 'index'])->name('index');
// 搜索接口
Route::get('search', [\App\Api\Shop\Controllers\SearchController::class, 'index'])->name('search');
