<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('api/member')->middleware('api')->group(function () {
    // 买家收货地址
    Route::get('address', [\App\Bundles\UMS\Controllers\Member\AddressController::class, 'index']);
    // 评论列表
    Route::get('comment', [\App\Bundles\CMS\Migrations\Comment\Controllers\Member\IndexController::class, 'index']);
    // 会员个人资料
    Route::get('profile', [\App\Bundles\UMS\Controllers\Member\ProfileController::class, 'index']);
});
// end
