<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询管理员操作权限列表接口
Route::post('adminAction/query', [\App\Bundles\Admin\Controllers\AdminActionController::class, 'query']);
// 新增管理员操作权限接口
Route::post('adminAction/store', [\App\Bundles\Admin\Controllers\AdminActionController::class, 'store']);
// 获取管理员操作权限详情接口
Route::get('adminAction/show', [\App\Bundles\Admin\Controllers\AdminActionController::class, 'show'])->name('adminAction.show');
// 更新管理员操作权限接口
Route::put('adminAction/update', [\App\Bundles\Admin\Controllers\AdminActionController::class, 'update']);
// 删除管理员操作权限接口
Route::delete('adminAction/destroy', [\App\Bundles\Admin\Controllers\AdminActionController::class, 'destroy']);
// 查询管理员操作日志列表接口
Route::post('adminLog/query', [\App\Bundles\Admin\Controllers\AdminLogController::class, 'query']);
// 新增管理员操作日志接口
Route::post('adminLog/store', [\App\Bundles\Admin\Controllers\AdminLogController::class, 'store']);
// 获取管理员操作日志详情接口
Route::get('adminLog/show', [\App\Bundles\Admin\Controllers\AdminLogController::class, 'show'])->name('adminLog.show');
// 更新管理员操作日志接口
Route::put('adminLog/update', [\App\Bundles\Admin\Controllers\AdminLogController::class, 'update']);
// 删除管理员操作日志接口
Route::delete('adminLog/destroy', [\App\Bundles\Admin\Controllers\AdminLogController::class, 'destroy']);
// 查询管理员消息列表接口
Route::post('adminMessage/query', [\App\Bundles\Admin\Controllers\AdminMessageController::class, 'query']);
// 新增管理员消息接口
Route::post('adminMessage/store', [\App\Bundles\Admin\Controllers\AdminMessageController::class, 'store']);
// 获取管理员消息详情接口
Route::get('adminMessage/show', [\App\Bundles\Admin\Controllers\AdminMessageController::class, 'show'])->name('adminMessage.show');
// 更新管理员消息接口
Route::put('adminMessage/update', [\App\Bundles\Admin\Controllers\AdminMessageController::class, 'update']);
// 删除管理员消息接口
Route::delete('adminMessage/destroy', [\App\Bundles\Admin\Controllers\AdminMessageController::class, 'destroy']);
// 查询管理员角色列表接口
Route::post('adminRole/query', [\App\Bundles\Admin\Controllers\AdminRoleController::class, 'query']);
// 新增管理员角色接口
Route::post('adminRole/store', [\App\Bundles\Admin\Controllers\AdminRoleController::class, 'store']);
// 获取管理员角色详情接口
Route::get('adminRole/show', [\App\Bundles\Admin\Controllers\AdminRoleController::class, 'show'])->name('adminRole.show');
// 更新管理员角色接口
Route::put('adminRole/update', [\App\Bundles\Admin\Controllers\AdminRoleController::class, 'update']);
// 删除管理员角色接口
Route::delete('adminRole/destroy', [\App\Bundles\Admin\Controllers\AdminRoleController::class, 'destroy']);
// 查询管理员用户列表接口
Route::post('adminUser/query', [\App\Bundles\Admin\Controllers\AdminUserController::class, 'query']);
// 新增管理员用户接口
Route::post('adminUser/store', [\App\Bundles\Admin\Controllers\AdminUserController::class, 'store']);
// 获取管理员用户详情接口
Route::get('adminUser/show', [\App\Bundles\Admin\Controllers\AdminUserController::class, 'show'])->name('adminUser.show');
// 更新管理员用户接口
Route::put('adminUser/update', [\App\Bundles\Admin\Controllers\AdminUserController::class, 'update']);
// 删除管理员用户接口
Route::delete('adminUser/destroy', [\App\Bundles\Admin\Controllers\AdminUserController::class, 'destroy']);
