<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询拍卖活动列表接口
Route::post('activityAuction/query', [\App\Bundles\Activity\Controllers\ActivityAuctionController::class, 'query']);
// 新增拍卖活动接口
Route::post('activityAuction/store', [\App\Bundles\Activity\Controllers\ActivityAuctionController::class, 'store']);
// 获取拍卖活动详情接口
Route::get('activityAuction/show', [\App\Bundles\Activity\Controllers\ActivityAuctionController::class, 'show'])->name('activityAuction.show');
// 更新拍卖活动接口
Route::put('activityAuction/update', [\App\Bundles\Activity\Controllers\ActivityAuctionController::class, 'update']);
// 删除拍卖活动接口
Route::delete('activityAuction/destroy', [\App\Bundles\Activity\Controllers\ActivityAuctionController::class, 'destroy']);
// 查询红包活动列表接口
Route::post('activityBonus/query', [\App\Bundles\Activity\Controllers\ActivityBonusController::class, 'query']);
// 新增红包活动接口
Route::post('activityBonus/store', [\App\Bundles\Activity\Controllers\ActivityBonusController::class, 'store']);
// 获取红包活动详情接口
Route::get('activityBonus/show', [\App\Bundles\Activity\Controllers\ActivityBonusController::class, 'show'])->name('activityBonus.show');
// 更新红包活动接口
Route::put('activityBonus/update', [\App\Bundles\Activity\Controllers\ActivityBonusController::class, 'update']);
// 删除红包活动接口
Route::delete('activityBonus/destroy', [\App\Bundles\Activity\Controllers\ActivityBonusController::class, 'destroy']);
// 查询促销活动列表接口
Route::post('activity/query', [\App\Bundles\Activity\Controllers\ActivityController::class, 'query']);
// 新增促销活动接口
Route::post('activity/store', [\App\Bundles\Activity\Controllers\ActivityController::class, 'store']);
// 获取促销活动详情接口
Route::get('activity/show', [\App\Bundles\Activity\Controllers\ActivityController::class, 'show'])->name('activity.show');
// 更新促销活动接口
Route::put('activity/update', [\App\Bundles\Activity\Controllers\ActivityController::class, 'update']);
// 删除促销活动接口
Route::delete('activity/destroy', [\App\Bundles\Activity\Controllers\ActivityController::class, 'destroy']);
// 查询积分兑换活动列表接口
Route::post('activityExchange/query', [\App\Bundles\Activity\Controllers\ActivityExchangeController::class, 'query']);
// 新增积分兑换活动接口
Route::post('activityExchange/store', [\App\Bundles\Activity\Controllers\ActivityExchangeController::class, 'store']);
// 获取积分兑换活动详情接口
Route::get('activityExchange/show', [\App\Bundles\Activity\Controllers\ActivityExchangeController::class, 'show'])->name('activityExchange.show');
// 更新积分兑换活动接口
Route::put('activityExchange/update', [\App\Bundles\Activity\Controllers\ActivityExchangeController::class, 'update']);
// 删除积分兑换活动接口
Route::delete('activityExchange/destroy', [\App\Bundles\Activity\Controllers\ActivityExchangeController::class, 'destroy']);
// 查询团购活动列表接口
Route::post('activityGroup/query', [\App\Bundles\Activity\Controllers\ActivityGroupController::class, 'query']);
// 新增团购活动接口
Route::post('activityGroup/store', [\App\Bundles\Activity\Controllers\ActivityGroupController::class, 'store']);
// 获取团购活动详情接口
Route::get('activityGroup/show', [\App\Bundles\Activity\Controllers\ActivityGroupController::class, 'show'])->name('activityGroup.show');
// 更新团购活动接口
Route::put('activityGroup/update', [\App\Bundles\Activity\Controllers\ActivityGroupController::class, 'update']);
// 删除团购活动接口
Route::delete('activityGroup/destroy', [\App\Bundles\Activity\Controllers\ActivityGroupController::class, 'destroy']);
// 查询超值礼包活动列表接口
Route::post('activityPackage/query', [\App\Bundles\Activity\Controllers\ActivityPackageController::class, 'query']);
// 新增超值礼包活动接口
Route::post('activityPackage/store', [\App\Bundles\Activity\Controllers\ActivityPackageController::class, 'store']);
// 获取超值礼包活动详情接口
Route::get('activityPackage/show', [\App\Bundles\Activity\Controllers\ActivityPackageController::class, 'show'])->name('activityPackage.show');
// 更新超值礼包活动接口
Route::put('activityPackage/update', [\App\Bundles\Activity\Controllers\ActivityPackageController::class, 'update']);
// 删除超值礼包活动接口
Route::delete('activityPackage/destroy', [\App\Bundles\Activity\Controllers\ActivityPackageController::class, 'destroy']);
// 查询夺宝奇兵活动列表接口
Route::post('activitySnatch/query', [\App\Bundles\Activity\Controllers\ActivitySnatchController::class, 'query']);
// 新增夺宝奇兵活动接口
Route::post('activitySnatch/store', [\App\Bundles\Activity\Controllers\ActivitySnatchController::class, 'store']);
// 获取夺宝奇兵活动详情接口
Route::get('activitySnatch/show', [\App\Bundles\Activity\Controllers\ActivitySnatchController::class, 'show'])->name('activitySnatch.show');
// 更新夺宝奇兵活动接口
Route::put('activitySnatch/update', [\App\Bundles\Activity\Controllers\ActivitySnatchController::class, 'update']);
// 删除夺宝奇兵活动接口
Route::delete('activitySnatch/destroy', [\App\Bundles\Activity\Controllers\ActivitySnatchController::class, 'destroy']);
// 查询专题活动列表接口
Route::post('activityTopic/query', [\App\Bundles\Activity\Controllers\ActivityTopicController::class, 'query']);
// 新增专题活动接口
Route::post('activityTopic/store', [\App\Bundles\Activity\Controllers\ActivityTopicController::class, 'store']);
// 获取专题活动详情接口
Route::get('activityTopic/show', [\App\Bundles\Activity\Controllers\ActivityTopicController::class, 'show'])->name('activityTopic.show');
// 更新专题活动接口
Route::put('activityTopic/update', [\App\Bundles\Activity\Controllers\ActivityTopicController::class, 'update']);
// 删除专题活动接口
Route::delete('activityTopic/destroy', [\App\Bundles\Activity\Controllers\ActivityTopicController::class, 'destroy']);
// 查询批发活动列表接口
Route::post('activityWholesale/query', [\App\Bundles\Activity\Controllers\ActivityWholesaleController::class, 'query']);
// 新增批发活动接口
Route::post('activityWholesale/store', [\App\Bundles\Activity\Controllers\ActivityWholesaleController::class, 'store']);
// 获取批发活动详情接口
Route::get('activityWholesale/show', [\App\Bundles\Activity\Controllers\ActivityWholesaleController::class, 'show'])->name('activityWholesale.show');
// 更新批发活动接口
Route::put('activityWholesale/update', [\App\Bundles\Activity\Controllers\ActivityWholesaleController::class, 'update']);
// 删除批发活动接口
Route::delete('activityWholesale/destroy', [\App\Bundles\Activity\Controllers\ActivityWholesaleController::class, 'destroy']);
