<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Modules\Portal\Controllers\CartController;
use App\Modules\Portal\Controllers\GoodsController;
use App\Modules\Portal\Controllers\HomeController;
use App\Modules\Portal\Controllers\OrderController;
use Illuminate\Support\Facades\Route;

// 前台购物车页面
Route::get('cart', [CartController::class, 'index'])->name('cart');
// 前台商品列表与搜索页
Route::get('goods', [GoodsController::class, 'index'])->name('goods');
// 前台商品详情页
Route::get('goods/{id}', [GoodsController::class, 'show'])->name('goods.{id}');
// PC 前台商城首页
Route::get('/', [HomeController::class, 'index'])->name('index');
// 订单确认结算页
Route::get('checkout', [OrderController::class, 'checkout'])->name('checkout');
// 收银台在线支付页
Route::get('pay/{orderNo}', [OrderController::class, 'pay'])->name('pay.{orderNo}');
// 前台用户订单中心
Route::get('orders', [OrderController::class, 'myOrders'])->name('orders');
