<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询用户反馈列表接口
Route::post('feedback/query', [\App\Bundles\Feedback\Controllers\FeedbackController::class, 'query']);
// 新增用户反馈接口
Route::post('feedback/store', [\App\Bundles\Feedback\Controllers\FeedbackController::class, 'store']);
// 获取用户反馈详情接口
Route::get('feedback/show', [\App\Bundles\Feedback\Controllers\FeedbackController::class, 'show'])->name('feedback.show');
// 更新用户反馈接口
Route::put('feedback/update', [\App\Bundles\Feedback\Controllers\FeedbackController::class, 'update']);
// 删除用户反馈接口
Route::delete('feedback/destroy', [\App\Bundles\Feedback\Controllers\FeedbackController::class, 'destroy']);
