<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询订单操作记录列表接口
Route::post('orderAction/query', [\App\Bundles\Order\Controllers\OrderActionController::class, 'query']);
// 新增订单操作记录接口
Route::post('orderAction/store', [\App\Bundles\Order\Controllers\OrderActionController::class, 'store']);
// 获取订单操作记录详情接口
Route::get('orderAction/show', [\App\Bundles\Order\Controllers\OrderActionController::class, 'show'])->name('orderAction.show');
// 更新订单操作记录接口
Route::put('orderAction/update', [\App\Bundles\Order\Controllers\OrderActionController::class, 'update']);
// 删除订单操作记录接口
Route::delete('orderAction/destroy', [\App\Bundles\Order\Controllers\OrderActionController::class, 'destroy']);
// 查询退货商品列表接口
Route::post('orderBackGoods/query', [\App\Bundles\Order\Controllers\OrderBackGoodsController::class, 'query']);
// 新增退货商品接口
Route::post('orderBackGoods/store', [\App\Bundles\Order\Controllers\OrderBackGoodsController::class, 'store']);
// 获取退货商品详情接口
Route::get('orderBackGoods/show', [\App\Bundles\Order\Controllers\OrderBackGoodsController::class, 'show'])->name('orderBackGoods.show');
// 更新退货商品接口
Route::put('orderBackGoods/update', [\App\Bundles\Order\Controllers\OrderBackGoodsController::class, 'update']);
// 删除退货商品接口
Route::delete('orderBackGoods/destroy', [\App\Bundles\Order\Controllers\OrderBackGoodsController::class, 'destroy']);
// 查询退货订单列表接口
Route::post('orderBackOrder/query', [\App\Bundles\Order\Controllers\OrderBackOrderController::class, 'query']);
// 新增退货订单接口
Route::post('orderBackOrder/store', [\App\Bundles\Order\Controllers\OrderBackOrderController::class, 'store']);
// 获取退货订单详情接口
Route::get('orderBackOrder/show', [\App\Bundles\Order\Controllers\OrderBackOrderController::class, 'show'])->name('orderBackOrder.show');
// 更新退货订单接口
Route::put('orderBackOrder/update', [\App\Bundles\Order\Controllers\OrderBackOrderController::class, 'update']);
// 删除退货订单接口
Route::delete('orderBackOrder/destroy', [\App\Bundles\Order\Controllers\OrderBackOrderController::class, 'destroy']);
// 查询发货商品列表接口
Route::post('orderDeliveryGoods/query', [\App\Bundles\Order\Controllers\OrderDeliveryGoodsController::class, 'query']);
// 新增发货商品接口
Route::post('orderDeliveryGoods/store', [\App\Bundles\Order\Controllers\OrderDeliveryGoodsController::class, 'store']);
// 获取发货商品详情接口
Route::get('orderDeliveryGoods/show', [\App\Bundles\Order\Controllers\OrderDeliveryGoodsController::class, 'show'])->name('orderDeliveryGoods.show');
// 更新发货商品接口
Route::put('orderDeliveryGoods/update', [\App\Bundles\Order\Controllers\OrderDeliveryGoodsController::class, 'update']);
// 删除发货商品接口
Route::delete('orderDeliveryGoods/destroy', [\App\Bundles\Order\Controllers\OrderDeliveryGoodsController::class, 'destroy']);
// 查询发货订单列表接口
Route::post('orderDeliveryOrder/query', [\App\Bundles\Order\Controllers\OrderDeliveryOrderController::class, 'query']);
// 新增发货订单接口
Route::post('orderDeliveryOrder/store', [\App\Bundles\Order\Controllers\OrderDeliveryOrderController::class, 'store']);
// 获取发货订单详情接口
Route::get('orderDeliveryOrder/show', [\App\Bundles\Order\Controllers\OrderDeliveryOrderController::class, 'show'])->name('orderDeliveryOrder.show');
// 更新发货订单接口
Route::put('orderDeliveryOrder/update', [\App\Bundles\Order\Controllers\OrderDeliveryOrderController::class, 'update']);
// 删除发货订单接口
Route::delete('orderDeliveryOrder/destroy', [\App\Bundles\Order\Controllers\OrderDeliveryOrderController::class, 'destroy']);
// 查询订单商品列表接口
Route::post('orderGoods/query', [\App\Bundles\Order\Controllers\OrderGoodsController::class, 'query']);
// 新增订单商品接口
Route::post('orderGoods/store', [\App\Bundles\Order\Controllers\OrderGoodsController::class, 'store']);
// 获取订单商品详情接口
Route::get('orderGoods/show', [\App\Bundles\Order\Controllers\OrderGoodsController::class, 'show'])->name('orderGoods.show');
// 更新订单商品接口
Route::put('orderGoods/update', [\App\Bundles\Order\Controllers\OrderGoodsController::class, 'update']);
// 删除订单商品接口
Route::delete('orderGoods/destroy', [\App\Bundles\Order\Controllers\OrderGoodsController::class, 'destroy']);
// 查询订单信息列表接口
Route::post('orderInfo/query', [\App\Bundles\Order\Controllers\OrderInfoController::class, 'query']);
// 新增订单信息接口
Route::post('orderInfo/store', [\App\Bundles\Order\Controllers\OrderInfoController::class, 'store']);
// 获取订单信息详情接口
Route::get('orderInfo/show', [\App\Bundles\Order\Controllers\OrderInfoController::class, 'show'])->name('orderInfo.show');
// 更新订单信息接口
Route::put('orderInfo/update', [\App\Bundles\Order\Controllers\OrderInfoController::class, 'update']);
// 删除订单信息接口
Route::delete('orderInfo/destroy', [\App\Bundles\Order\Controllers\OrderInfoController::class, 'destroy']);
// 查询订单支付记录列表接口
Route::post('orderPay/query', [\App\Bundles\Order\Controllers\OrderPayController::class, 'query']);
// 新增订单支付记录接口
Route::post('orderPay/store', [\App\Bundles\Order\Controllers\OrderPayController::class, 'store']);
// 获取订单支付记录详情接口
Route::get('orderPay/show', [\App\Bundles\Order\Controllers\OrderPayController::class, 'show'])->name('orderPay.show');
// 更新订单支付记录接口
Route::put('orderPay/update', [\App\Bundles\Order\Controllers\OrderPayController::class, 'update']);
// 删除订单支付记录接口
Route::delete('orderPay/destroy', [\App\Bundles\Order\Controllers\OrderPayController::class, 'destroy']);
