<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('api/portal')->middleware('api')->group(function () {
    // 附件上传接口
    Route::post('upload', [\App\Bundles\Material\Controllers\Portal\UploadController::class, 'index']);
    // 图片验证码
    Route::get('captcha', [\App\Bundles\Captcha\Controllers\Portal\CaptchaController::class, 'index'])->name('captcha');
    // 查询地区列表
    Route::get('region', [\App\Bundles\Region\Controllers\Portal\RegionController::class, 'index'])->name('region');
    // 发送手机短信验证码
    Route::post('sms', [\App\Bundles\Sms\Controllers\Portal\SmsController::class, 'index']);
});
// end
