<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Api\Portal\Controllers\ArticleController;
use App\Api\Portal\Controllers\BannerController;
use App\Api\Portal\Controllers\CategoryController;
use App\Api\Portal\Controllers\HelpCenterController;
use App\Api\Portal\Controllers\IndexController;
use App\Api\Portal\Controllers\MarketingController;
use App\Api\Portal\Controllers\NoticeController;
use App\Api\Portal\Controllers\ProductController;
use App\Api\Portal\Controllers\SearchController;
use App\Api\Portal\Controllers\SeckillController;
use App\Api\Portal\Controllers\ShopController;
use Illuminate\Support\Facades\Route;

// 文章列表
Route::get('articles', [ArticleController::class, 'index'])->name('articles');
// 文章详情
Route::get('articles/{id}', [ArticleController::class, 'show'])->name('articles.{id}');
// 轮播图列表
Route::get('banners', [BannerController::class, 'index'])->name('banners');
// 分类列表
Route::get('categories', [CategoryController::class, 'index'])->name('categories');
// 分类树
Route::get('categories/tree', [CategoryController::class, 'tree'])->name('categories.tree');
// 帮助中心列表
Route::get('help-center', [HelpCenterController::class, 'index'])->name('help-center');
// 帮助中心详情
Route::get('help-center/{id}', [HelpCenterController::class, 'show'])->name('help-center.{id}');
// 帮助中心搜索
Route::get('help-center/search', [HelpCenterController::class, 'search'])->name('help-center.search');
// 帮助中心分类
Route::get('help-center/categories', [HelpCenterController::class, 'categories'])->name('help-center.categories');
// 首页
Route::get('/', [IndexController::class, 'index'])->name('index');
// 营销活动列表
Route::get('marketing', [MarketingController::class, 'index'])->name('marketing');
// 当前营销活动
Route::get('marketing/current', [MarketingController::class, 'current'])->name('marketing.current');
// 即将开始营销活动
Route::get('marketing/upcoming', [MarketingController::class, 'upcoming'])->name('marketing.upcoming');
// 公告列表
Route::get('notices', [NoticeController::class, 'index'])->name('notices');
// 公告详情
Route::get('notices/{id}', [NoticeController::class, 'show'])->name('notices.{id}');
// 商品列表
Route::get('products', [ProductController::class, 'index'])->name('products');
// 商品详情
Route::get('products/{id}', [ProductController::class, 'show'])->name('products.{id}');
// 推荐商品
Route::get('products/recommend', [ProductController::class, 'recommend'])->name('products.recommend');
// 热销商品
Route::get('products/hot', [ProductController::class, 'hot'])->name('products.hot');
// 商品评价列表
Route::get('products/{id}/reviews', [ProductController::class, 'reviews'])->name('products.{id}.reviews');
// 搜索接口
Route::get('search', [SearchController::class, 'index'])->name('search');
// 商品搜索
Route::get('search/products', [SearchController::class, 'products'])->name('search.products');
// 搜索建议
Route::get('search/suggest', [SearchController::class, 'suggest'])->name('search.suggest');
// 热搜关键词
Route::get('search/hot-keywords', [SearchController::class, 'hotKeywords'])->name('search.hot-keywords');
// 搜索筛选条件
Route::get('search/filters', [SearchController::class, 'filters'])->name('search.filters');
// 秒杀活动列表
Route::get('seckills', [SeckillController::class, 'index'])->name('seckills');
// 秒杀活动详情
Route::get('seckills/{id}', [SeckillController::class, 'show'])->name('seckills.{id}');
// 店铺列表
Route::get('shops', [ShopController::class, 'index'])->name('shops');
// 店铺详情
Route::get('shops/{id}', [ShopController::class, 'show'])->name('shops.{id}');
