openapi: 3.0.0
info:
  title: API文档
  description: 门户平台接口
  contact:
    name: 'API Develop Team'
  version: '1.0'
servers:
  -
    url: 'http://127.0.0.1:8000'
    description: 开发环境
  -
    url: 'https://demo.phpmall.net'
    description: 测试环境
paths:
  /portal/catalog:
    get:
      tags:
        - 类目
      summary: 全部类目
      operationId: 0a23c01ab93810102beb4a50d6a59a40
      responses:
        '200':
          description: OK
  /portal/category:
    get:
      tags:
        - 商品分类
      summary: 商品分类
      operationId: ee46b018123067237cbe29e6399becd4
      responses:
        '200':
          description: OK
  /portal:
    get:
      tags:
        - 首页
      summary: 商城首页
      operationId: d703d3960c095f9c0ac501110f0579b8
      responses:
        '200':
          description: OK
