<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询评论列表接口
Route::post('comment/query', [\App\Bundles\Comment\Controllers\CommentController::class, 'query']);
// 新增评论接口
Route::post('comment/store', [\App\Bundles\Comment\Controllers\CommentController::class, 'store']);
// 获取评论详情接口
Route::get('comment/show', [\App\Bundles\Comment\Controllers\CommentController::class, 'show'])->name('comment.show');
// 更新评论接口
Route::put('comment/update', [\App\Bundles\Comment\Controllers\CommentController::class, 'update']);
// 删除评论接口
Route::delete('comment/destroy', [\App\Bundles\Comment\Controllers\CommentController::class, 'destroy']);
