<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询供应商列表接口
Route::post('supplier/query', [\App\Bundles\Supplier\Controllers\SupplierController::class, 'query']);
// 新增供应商接口
Route::post('supplier/store', [\App\Bundles\Supplier\Controllers\SupplierController::class, 'store']);
// 获取供应商详情接口
Route::get('supplier/show', [\App\Bundles\Supplier\Controllers\SupplierController::class, 'show'])->name('supplier.show');
// 更新供应商接口
Route::put('supplier/update', [\App\Bundles\Supplier\Controllers\SupplierController::class, 'update']);
// 删除供应商接口
Route::delete('supplier/destroy', [\App\Bundles\Supplier\Controllers\SupplierController::class, 'destroy']);
