<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询文章分类列表接口
Route::post('articleCat/query', [\App\Bundles\Article\Controllers\ArticleCatController::class, 'query']);
// 新增文章分类接口
Route::post('articleCat/store', [\App\Bundles\Article\Controllers\ArticleCatController::class, 'store']);
// 获取文章分类详情接口
Route::get('articleCat/show', [\App\Bundles\Article\Controllers\ArticleCatController::class, 'show'])->name('articleCat.show');
// 更新文章分类接口
Route::put('articleCat/update', [\App\Bundles\Article\Controllers\ArticleCatController::class, 'update']);
// 删除文章分类接口
Route::delete('articleCat/destroy', [\App\Bundles\Article\Controllers\ArticleCatController::class, 'destroy']);
// 查询文章列表接口
Route::post('article/query', [\App\Bundles\Article\Controllers\ArticleController::class, 'query']);
// 新增文章接口
Route::post('article/store', [\App\Bundles\Article\Controllers\ArticleController::class, 'store']);
// 获取文章详情接口
Route::get('article/show', [\App\Bundles\Article\Controllers\ArticleController::class, 'show'])->name('article.show');
// 更新文章接口
Route::put('article/update', [\App\Bundles\Article\Controllers\ArticleController::class, 'update']);
// 删除文章接口
Route::delete('article/destroy', [\App\Bundles\Article\Controllers\ArticleController::class, 'destroy']);
