<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Domains\Order\Controllers\OrderController;
use App\Domains\Order\Controllers\OrderItemController;
use App\Domains\Order\Controllers\OrderRefundController;
use App\Domains\Order\Controllers\OrderShipmentController;
use Illuminate\Support\Facades\Route;

// 查询订单列表接口
Route::post('order/search', [OrderController::class, 'search']);
// 新增订单接口
Route::post('order/store', [OrderController::class, 'store']);
// 获取订单详情接口
Route::get('order/show', [OrderController::class, 'show'])->name('order.show');
// 更新订单接口
Route::put('order/update', [OrderController::class, 'update']);
// 删除订单接口
Route::post('order/destroy', [OrderController::class, 'destroy']);
// 查询订单商品明细列表接口
Route::post('orderItem/search', [OrderItemController::class, 'search']);
// 新增订单商品明细接口
Route::post('orderItem/store', [OrderItemController::class, 'store']);
// 获取订单商品明细详情接口
Route::get('orderItem/show', [OrderItemController::class, 'show'])->name('orderItem.show');
// 更新订单商品明细接口
Route::put('orderItem/update', [OrderItemController::class, 'update']);
// 删除订单商品明细接口
Route::post('orderItem/destroy', [OrderItemController::class, 'destroy']);
// 查询订单退款售后列表接口
Route::post('orderRefund/search', [OrderRefundController::class, 'search']);
// 新增订单退款售后接口
Route::post('orderRefund/store', [OrderRefundController::class, 'store']);
// 获取订单退款售后详情接口
Route::get('orderRefund/show', [OrderRefundController::class, 'show'])->name('orderRefund.show');
// 更新订单退款售后接口
Route::put('orderRefund/update', [OrderRefundController::class, 'update']);
// 删除订单退款售后接口
Route::post('orderRefund/destroy', [OrderRefundController::class, 'destroy']);
// 查询订单物流发货列表接口
Route::post('orderShipment/search', [OrderShipmentController::class, 'search']);
// 新增订单物流发货接口
Route::post('orderShipment/store', [OrderShipmentController::class, 'store']);
// 获取订单物流发货详情接口
Route::get('orderShipment/show', [OrderShipmentController::class, 'show'])->name('orderShipment.show');
// 更新订单物流发货接口
Route::put('orderShipment/update', [OrderShipmentController::class, 'update']);
// 删除订单物流发货接口
Route::post('orderShipment/destroy', [OrderShipmentController::class, 'destroy']);
