<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询办事处列表接口
Route::post('shopAgency/query', [\App\Bundles\Shop\Controllers\ShopAgencyController::class, 'query']);
// 新增办事处接口
Route::post('shopAgency/store', [\App\Bundles\Shop\Controllers\ShopAgencyController::class, 'store']);
// 获取办事处详情接口
Route::get('shopAgency/show', [\App\Bundles\Shop\Controllers\ShopAgencyController::class, 'show'])->name('shopAgency.show');
// 更新办事处接口
Route::put('shopAgency/update', [\App\Bundles\Shop\Controllers\ShopAgencyController::class, 'update']);
// 删除办事处接口
Route::delete('shopAgency/destroy', [\App\Bundles\Shop\Controllers\ShopAgencyController::class, 'destroy']);
// 查询自动管理列表接口
Route::post('shopAutoManage/query', [\App\Bundles\Shop\Controllers\ShopAutoManageController::class, 'query']);
// 新增自动管理接口
Route::post('shopAutoManage/store', [\App\Bundles\Shop\Controllers\ShopAutoManageController::class, 'store']);
// 获取自动管理详情接口
Route::get('shopAutoManage/show', [\App\Bundles\Shop\Controllers\ShopAutoManageController::class, 'show'])->name('shopAutoManage.show');
// 更新自动管理接口
Route::put('shopAutoManage/update', [\App\Bundles\Shop\Controllers\ShopAutoManageController::class, 'update']);
// 删除自动管理接口
Route::delete('shopAutoManage/destroy', [\App\Bundles\Shop\Controllers\ShopAutoManageController::class, 'destroy']);
// 查询贺卡列表接口
Route::post('shopCard/query', [\App\Bundles\Shop\Controllers\ShopCardController::class, 'query']);
// 新增贺卡接口
Route::post('shopCard/store', [\App\Bundles\Shop\Controllers\ShopCardController::class, 'store']);
// 获取贺卡详情接口
Route::get('shopCard/show', [\App\Bundles\Shop\Controllers\ShopCardController::class, 'show'])->name('shopCard.show');
// 更新贺卡接口
Route::put('shopCard/update', [\App\Bundles\Shop\Controllers\ShopCardController::class, 'update']);
// 删除贺卡接口
Route::delete('shopCard/destroy', [\App\Bundles\Shop\Controllers\ShopCardController::class, 'destroy']);
// 查询商店配置列表接口
Route::post('shopConfig/query', [\App\Bundles\Shop\Controllers\ShopConfigController::class, 'query']);
// 新增商店配置接口
Route::post('shopConfig/store', [\App\Bundles\Shop\Controllers\ShopConfigController::class, 'store']);
// 获取商店配置详情接口
Route::get('shopConfig/show', [\App\Bundles\Shop\Controllers\ShopConfigController::class, 'show'])->name('shopConfig.show');
// 更新商店配置接口
Route::put('shopConfig/update', [\App\Bundles\Shop\Controllers\ShopConfigController::class, 'update']);
// 删除商店配置接口
Route::delete('shopConfig/destroy', [\App\Bundles\Shop\Controllers\ShopConfigController::class, 'destroy']);
// 查询计划任务列表接口
Route::post('shopCron/query', [\App\Bundles\Shop\Controllers\ShopCronController::class, 'query']);
// 新增计划任务接口
Route::post('shopCron/store', [\App\Bundles\Shop\Controllers\ShopCronController::class, 'store']);
// 获取计划任务详情接口
Route::get('shopCron/show', [\App\Bundles\Shop\Controllers\ShopCronController::class, 'show'])->name('shopCron.show');
// 更新计划任务接口
Route::put('shopCron/update', [\App\Bundles\Shop\Controllers\ShopCronController::class, 'update']);
// 删除计划任务接口
Route::delete('shopCron/destroy', [\App\Bundles\Shop\Controllers\ShopCronController::class, 'destroy']);
// 查询错误日志列表接口
Route::post('shopErrorLog/query', [\App\Bundles\Shop\Controllers\ShopErrorLogController::class, 'query']);
// 新增错误日志接口
Route::post('shopErrorLog/store', [\App\Bundles\Shop\Controllers\ShopErrorLogController::class, 'store']);
// 获取错误日志详情接口
Route::get('shopErrorLog/show', [\App\Bundles\Shop\Controllers\ShopErrorLogController::class, 'show'])->name('shopErrorLog.show');
// 更新错误日志接口
Route::put('shopErrorLog/update', [\App\Bundles\Shop\Controllers\ShopErrorLogController::class, 'update']);
// 删除错误日志接口
Route::delete('shopErrorLog/destroy', [\App\Bundles\Shop\Controllers\ShopErrorLogController::class, 'destroy']);
// 查询友情链接列表接口
Route::post('shopFriendLink/query', [\App\Bundles\Shop\Controllers\ShopFriendLinkController::class, 'query']);
// 新增友情链接接口
Route::post('shopFriendLink/store', [\App\Bundles\Shop\Controllers\ShopFriendLinkController::class, 'store']);
// 获取友情链接详情接口
Route::get('shopFriendLink/show', [\App\Bundles\Shop\Controllers\ShopFriendLinkController::class, 'show'])->name('shopFriendLink.show');
// 更新友情链接接口
Route::put('shopFriendLink/update', [\App\Bundles\Shop\Controllers\ShopFriendLinkController::class, 'update']);
// 删除友情链接接口
Route::delete('shopFriendLink/destroy', [\App\Bundles\Shop\Controllers\ShopFriendLinkController::class, 'destroy']);
// 查询导航菜单列表接口
Route::post('shopNav/query', [\App\Bundles\Shop\Controllers\ShopNavController::class, 'query']);
// 新增导航菜单接口
Route::post('shopNav/store', [\App\Bundles\Shop\Controllers\ShopNavController::class, 'store']);
// 获取导航菜单详情接口
Route::get('shopNav/show', [\App\Bundles\Shop\Controllers\ShopNavController::class, 'show'])->name('shopNav.show');
// 更新导航菜单接口
Route::put('shopNav/update', [\App\Bundles\Shop\Controllers\ShopNavController::class, 'update']);
// 删除导航菜单接口
Route::delete('shopNav/destroy', [\App\Bundles\Shop\Controllers\ShopNavController::class, 'destroy']);
// 查询包装列表接口
Route::post('shopPack/query', [\App\Bundles\Shop\Controllers\ShopPackController::class, 'query']);
// 新增包装接口
Route::post('shopPack/store', [\App\Bundles\Shop\Controllers\ShopPackController::class, 'store']);
// 获取包装详情接口
Route::get('shopPack/show', [\App\Bundles\Shop\Controllers\ShopPackController::class, 'show'])->name('shopPack.show');
// 更新包装接口
Route::put('shopPack/update', [\App\Bundles\Shop\Controllers\ShopPackController::class, 'update']);
// 删除包装接口
Route::delete('shopPack/destroy', [\App\Bundles\Shop\Controllers\ShopPackController::class, 'destroy']);
// 查询插件列表接口
Route::post('shopPlugins/query', [\App\Bundles\Shop\Controllers\ShopPluginsController::class, 'query']);
// 新增插件接口
Route::post('shopPlugins/store', [\App\Bundles\Shop\Controllers\ShopPluginsController::class, 'store']);
// 获取插件详情接口
Route::get('shopPlugins/show', [\App\Bundles\Shop\Controllers\ShopPluginsController::class, 'show'])->name('shopPlugins.show');
// 更新插件接口
Route::put('shopPlugins/update', [\App\Bundles\Shop\Controllers\ShopPluginsController::class, 'update']);
// 删除插件接口
Route::delete('shopPlugins/destroy', [\App\Bundles\Shop\Controllers\ShopPluginsController::class, 'destroy']);
// 查询地区列表接口
Route::post('shopRegion/query', [\App\Bundles\Shop\Controllers\ShopRegionController::class, 'query']);
// 新增地区接口
Route::post('shopRegion/store', [\App\Bundles\Shop\Controllers\ShopRegionController::class, 'store']);
// 获取地区详情接口
Route::get('shopRegion/show', [\App\Bundles\Shop\Controllers\ShopRegionController::class, 'show'])->name('shopRegion.show');
// 更新地区接口
Route::put('shopRegion/update', [\App\Bundles\Shop\Controllers\ShopRegionController::class, 'update']);
// 删除地区接口
Route::delete('shopRegion/destroy', [\App\Bundles\Shop\Controllers\ShopRegionController::class, 'destroy']);
// 查询统计列表接口
Route::post('shopStats/query', [\App\Bundles\Shop\Controllers\ShopStatsController::class, 'query']);
// 新增统计接口
Route::post('shopStats/store', [\App\Bundles\Shop\Controllers\ShopStatsController::class, 'store']);
// 获取统计详情接口
Route::get('shopStats/show', [\App\Bundles\Shop\Controllers\ShopStatsController::class, 'show'])->name('shopStats.show');
// 更新统计接口
Route::put('shopStats/update', [\App\Bundles\Shop\Controllers\ShopStatsController::class, 'update']);
// 删除统计接口
Route::delete('shopStats/destroy', [\App\Bundles\Shop\Controllers\ShopStatsController::class, 'destroy']);
