<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询邮件发送记录列表接口
Route::post('emailSend/query', [\App\Bundles\Email\Controllers\EmailSendController::class, 'query']);
// 新增邮件发送记录接口
Route::post('emailSend/store', [\App\Bundles\Email\Controllers\EmailSendController::class, 'store']);
// 获取邮件发送记录详情接口
Route::get('emailSend/show', [\App\Bundles\Email\Controllers\EmailSendController::class, 'show'])->name('emailSend.show');
// 更新邮件发送记录接口
Route::put('emailSend/update', [\App\Bundles\Email\Controllers\EmailSendController::class, 'update']);
// 删除邮件发送记录接口
Route::delete('emailSend/destroy', [\App\Bundles\Email\Controllers\EmailSendController::class, 'destroy']);
// 查询邮件订阅列表接口
Route::post('emailSubscriber/query', [\App\Bundles\Email\Controllers\EmailSubscriberController::class, 'query']);
// 新增邮件订阅接口
Route::post('emailSubscriber/store', [\App\Bundles\Email\Controllers\EmailSubscriberController::class, 'store']);
// 获取邮件订阅详情接口
Route::get('emailSubscriber/show', [\App\Bundles\Email\Controllers\EmailSubscriberController::class, 'show'])->name('emailSubscriber.show');
// 更新邮件订阅接口
Route::put('emailSubscriber/update', [\App\Bundles\Email\Controllers\EmailSubscriberController::class, 'update']);
// 删除邮件订阅接口
Route::delete('emailSubscriber/destroy', [\App\Bundles\Email\Controllers\EmailSubscriberController::class, 'destroy']);
// 查询邮件模板列表接口
Route::post('emailTemplate/query', [\App\Bundles\Email\Controllers\EmailTemplateController::class, 'query']);
// 新增邮件模板接口
Route::post('emailTemplate/store', [\App\Bundles\Email\Controllers\EmailTemplateController::class, 'store']);
// 获取邮件模板详情接口
Route::get('emailTemplate/show', [\App\Bundles\Email\Controllers\EmailTemplateController::class, 'show'])->name('emailTemplate.show');
// 更新邮件模板接口
Route::put('emailTemplate/update', [\App\Bundles\Email\Controllers\EmailTemplateController::class, 'update']);
// 删除邮件模板接口
Route::delete('emailTemplate/destroy', [\App\Bundles\Email\Controllers\EmailTemplateController::class, 'destroy']);
