<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
// 管理员接口
Route::get('admin', [\App\Api\Manager\Controllers\AdminController::class, 'index'])->name('admin');
// 运营首页
Route::get('admin/dashboard', [\App\Api\Manager\Controllers\DashboardController::class, 'index'])->name('admin.dashboard');
// 管理仪表台
Route::get('admin/index1', [\App\Api\Manager\Controllers\IndexController::class, 'index1'])->name('admin.index1');
// 权限列表
Route::get('admin/permission', [\App\Api\Manager\Controllers\PermissionController::class, 'index'])->name('admin.permission');
// 角色列表
Route::get('admin/role', [\App\Api\Manager\Controllers\RoleController::class, 'index'])->name('admin.role');
// 全部卖家
Route::get('admin/seller', [\App\Api\Manager\Controllers\SellerController::class, 'index'])->name('admin.seller');
// 卖家店铺
Route::get('admin/shop', [\App\Api\Manager\Controllers\ShopController::class, 'index'])->name('admin.shop');
// 卖家门店
Route::get('admin/store', [\App\Api\Manager\Controllers\StoreController::class, 'index'])->name('admin.store');
// 买家收货地址
Route::get('admin/userAddress', [\App\Api\Manager\Controllers\UserAddressController::class, 'index'])->name('admin.userAddress');
// 用户列表
Route::get('admin/user', [\App\Api\Manager\Controllers\UserController::class, 'index'])->name('admin.user');
// 添加新用户
Route::post('admin/user/store', [\App\Api\Manager\Controllers\UserController::class, 'store']);
// 获取详情
Route::get('admin/user/show', [\App\Api\Manager\Controllers\UserController::class, 'show'])->name('admin.user.show');
// 更新用户详情
Route::put('admin/user/update', [\App\Api\Manager\Controllers\UserController::class, 'update']);
// 删除用户
Route::delete('admin/user/destroy', [\App\Api\Manager\Controllers\UserController::class, 'destroy']);
// end
