<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('api/manager')->middleware('api')->group(function () {
    // 运营首页
    Route::get('dashboard', [\App\API\Manager\Controllers\DashboardController::class, 'index']);
    // 获取管理菜单
    Route::get('menu', [\App\API\Manager\Controllers\DashboardController::class, 'menu']);
    // 获取系统消息
    Route::get('message', [\App\API\Manager\Controllers\DashboardController::class, 'message']);
    // 运营首页
    Route::get('dashboard', [\App\Bundles\System\API\Manager\Controllers\DashboardController::class, 'index']);
    // 管理员信息
    Route::get('profile', [\App\Bundles\System\API\Manager\Controllers\IndexController::class, 'profile']);
    // 管理菜单
    Route::get('menu', [\App\Bundles\System\API\Manager\Controllers\IndexController::class, 'menu']);
    // 系统消息
    Route::get('message', [\App\Bundles\System\API\Manager\Controllers\IndexController::class, 'message']);
    // 修改密码
    Route::post('password', [\App\Bundles\System\API\Manager\Controllers\IndexController::class, 'password']);
    // 注销登录
    Route::post('logout', [\App\Bundles\System\API\Manager\Controllers\IndexController::class, 'logout']);
    // 管理员接口
    Route::get('manager', [\App\Bundles\System\API\Manager\Controllers\ManagerController::class, 'index']);
    // 查询列表接口
    Route::post('permission/query', [\App\Bundles\System\API\Manager\Controllers\PermissionController::class, 'query']);
    // 新增接口
    Route::post('permission/create', [\App\Bundles\System\API\Manager\Controllers\PermissionController::class, 'create']);
    // 获取详情接口
    Route::get('permission/show', [\App\Bundles\System\API\Manager\Controllers\PermissionController::class, 'show']);
    // 更新接口
    Route::put('permission/update', [\App\Bundles\System\API\Manager\Controllers\PermissionController::class, 'update']);
    // 删除接口
    Route::delete('permission/destroy', [\App\Bundles\System\API\Manager\Controllers\PermissionController::class, 'destroy']);
    // 运营首页
    Route::get('dashboard', [\App\Bundles\System\API\Manager\Controllers\ProfileController::class, 'dashboard']);
    // 获取管理菜单
    Route::get('menu', [\App\Bundles\System\API\Manager\Controllers\ProfileController::class, 'menu']);
    // 获取系统消息
    Route::get('message', [\App\Bundles\System\API\Manager\Controllers\ProfileController::class, 'message']);
    // 获取个人资料
    Route::get('profile', [\App\Bundles\System\API\Manager\Controllers\ProfileController::class, 'profile']);
    // 修改密码
    Route::post('password', [\App\Bundles\System\API\Manager\Controllers\ProfileController::class, 'password']);
    // 注销登录
    Route::post('logout', [\App\Bundles\System\API\Manager\Controllers\ProfileController::class, 'logout']);
    // 查询列表接口
    Route::post('role/query', [\App\Bundles\System\API\Manager\Controllers\RoleController::class, 'query']);
    // 新增接口
    Route::post('role/create', [\App\Bundles\System\API\Manager\Controllers\RoleController::class, 'create']);
    // 获取详情接口
    Route::get('role/show', [\App\Bundles\System\API\Manager\Controllers\RoleController::class, 'show']);
    // 更新接口
    Route::put('role/update', [\App\Bundles\System\API\Manager\Controllers\RoleController::class, 'update']);
    // 删除接口
    Route::delete('role/destroy', [\App\Bundles\System\API\Manager\Controllers\RoleController::class, 'destroy']);
    // 查询列表接口
    Route::post('rolePermission/query', [\App\Bundles\System\API\Manager\Controllers\RolePermissionController::class, 'query']);
    // 新增接口
    Route::post('rolePermission/create', [\App\Bundles\System\API\Manager\Controllers\RolePermissionController::class, 'create']);
    // 获取详情接口
    Route::get('rolePermission/show', [\App\Bundles\System\API\Manager\Controllers\RolePermissionController::class, 'show']);
    // 更新接口
    Route::put('rolePermission/update', [\App\Bundles\System\API\Manager\Controllers\RolePermissionController::class, 'update']);
    // 删除接口
    Route::delete('rolePermission/destroy', [\App\Bundles\System\API\Manager\Controllers\RolePermissionController::class, 'destroy']);
    // 查询列表接口
    Route::post('user/query', [\App\Bundles\System\API\Manager\Controllers\UserController::class, 'query']);
    // 新增接口
    Route::post('user/create', [\App\Bundles\System\API\Manager\Controllers\UserController::class, 'create']);
    // 获取详情接口
    Route::get('user/show', [\App\Bundles\System\API\Manager\Controllers\UserController::class, 'show']);
    // 更新接口
    Route::put('user/update', [\App\Bundles\System\API\Manager\Controllers\UserController::class, 'update']);
    // 删除接口
    Route::delete('user/destroy', [\App\Bundles\System\API\Manager\Controllers\UserController::class, 'destroy']);
    // 查询列表接口
    Route::post('userLog/query', [\App\Bundles\System\API\Manager\Controllers\UserLogController::class, 'query']);
    // 新增接口
    Route::post('userLog/create', [\App\Bundles\System\API\Manager\Controllers\UserLogController::class, 'create']);
    // 获取详情接口
    Route::get('userLog/show', [\App\Bundles\System\API\Manager\Controllers\UserLogController::class, 'show']);
    // 更新接口
    Route::put('userLog/update', [\App\Bundles\System\API\Manager\Controllers\UserLogController::class, 'update']);
    // 删除接口
    Route::delete('userLog/destroy', [\App\Bundles\System\API\Manager\Controllers\UserLogController::class, 'destroy']);
    // 查询列表接口
    Route::post('userPermission/query', [\App\Bundles\System\API\Manager\Controllers\UserPermissionController::class, 'query']);
    // 新增接口
    Route::post('userPermission/create', [\App\Bundles\System\API\Manager\Controllers\UserPermissionController::class, 'create']);
    // 获取详情接口
    Route::get('userPermission/show', [\App\Bundles\System\API\Manager\Controllers\UserPermissionController::class, 'show']);
    // 更新接口
    Route::put('userPermission/update', [\App\Bundles\System\API\Manager\Controllers\UserPermissionController::class, 'update']);
    // 删除接口
    Route::delete('userPermission/destroy', [\App\Bundles\System\API\Manager\Controllers\UserPermissionController::class, 'destroy']);
    // 查询列表接口
    Route::post('userRole/query', [\App\Bundles\System\API\Manager\Controllers\UserRoleController::class, 'query']);
    // 新增接口
    Route::post('userRole/create', [\App\Bundles\System\API\Manager\Controllers\UserRoleController::class, 'create']);
    // 获取详情接口
    Route::get('userRole/show', [\App\Bundles\System\API\Manager\Controllers\UserRoleController::class, 'show']);
    // 更新接口
    Route::put('userRole/update', [\App\Bundles\System\API\Manager\Controllers\UserRoleController::class, 'update']);
    // 删除接口
    Route::delete('userRole/destroy', [\App\Bundles\System\API\Manager\Controllers\UserRoleController::class, 'destroy']);
    // 买家收货地址
    Route::get('userAddress', [\App\Bundles\User\API\Manager\Controllers\UserAddressController::class, 'index']);
    // 用户列表
    Route::get('user', [\App\Bundles\User\API\Manager\Controllers\UserController::class, 'index']);
    // 添加新用户
    Route::post('user/store', [\App\Bundles\User\API\Manager\Controllers\UserController::class, 'store']);
    // 获取详情
    Route::get('user/show', [\App\Bundles\User\API\Manager\Controllers\UserController::class, 'show']);
    // 更新用户详情
    Route::put('user/update', [\App\Bundles\User\API\Manager\Controllers\UserController::class, 'update']);
    // 删除用户
    Route::delete('user/destroy', [\App\Bundles\User\API\Manager\Controllers\UserController::class, 'destroy']);
});
// end
