<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('api/supplier')->middleware('api')->group(function () {
    // supplier
    Route::get('supplier', [\App\Api\Supplier\Controllers\IndexController::class, 'index'])->name('supplier');
});
// end
