<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Modules\User\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('user/search', [UserController::class, 'search']);
// 新增接口
Route::post('user/store', [UserController::class, 'store']);
// 获取详情接口
Route::get('user/show', [UserController::class, 'show'])->name('user.show');
// 更新接口
Route::put('user/update', [UserController::class, 'update']);
// 删除接口
Route::post('user/destroy', [UserController::class, 'destroy']);
