<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
// 卖家
Route::get('seller', [\App\Api\Seller\Controllers\IndexController::class, 'index'])->name('seller');
// end
