<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('api/seller')->middleware('api')->group(function () {
    // 商家首页
    Route::get('dashboard', [\App\API\Seller\Controllers\DashboardController::class, 'index']);
    // 获取管理菜单
    Route::get('dashboard/menu', [\App\API\Seller\Controllers\DashboardController::class, 'menu']);
    // 获取系统消息
    Route::get('dashboard/message', [\App\API\Seller\Controllers\DashboardController::class, 'message']);
});
// end
