<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 商家登录接口
Route::post('auth/login', [\App\Api\Seller\Controllers\AuthController::class, 'login']);
// 首页
Route::get('/', [\App\Api\Seller\Controllers\IndexController::class, 'index'])->name('index');
