<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Api\User\Controllers\AuthController;
use App\Api\User\Controllers\IndexController;
use App\Api\User\Controllers\ProfileController;
use App\Api\User\Controllers\UserController;
use Illuminate\Support\Facades\Route;

// 新会员注册
Route::post('auth/signup', [AuthController::class, 'signup']);
// 会员登录接口
Route::post('auth/login', [AuthController::class, 'login']);
// 忘记密码
Route::post('auth/forgot-password', [AuthController::class, 'forgot']);
// 重置密码
Route::post('auth/reset-password', [AuthController::class, 'reset']);
// 会员登出
Route::post('auth/logout', [AuthController::class, 'logout']);
// 首页
Route::get('/', [IndexController::class, 'index'])->name('index');
// 获取会员资料
Route::get('profile', [ProfileController::class, 'index'])->name('profile');
// 更新会员资料
Route::put('profile', [ProfileController::class, 'update']);
// 获取会员资料
Route::get('me', [UserController::class, 'profile'])->name('me');
// 更新会员资料
Route::put('me', [UserController::class, 'updateProfile']);
// 收货地址相关路由由 app/Modules/User/Routes/route.gen.php 注册
// 此处保留接口定义在 App\Api\User\Controllers\AddressController 中供 OpenAPI 扫描
