<?php

// ==========================================================================
// Code generated by gen:bundle:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// web route start
Route::prefix('/')->group(function () {
    // 类目
    Route::get('catalog', [\App\Modules\Web\Controllers\CatalogController::class, 'index']);
    // 首页
    Route::get('/', [\App\Modules\Web\Controllers\IndexController::class, 'index']);
});
// end
