<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('api/common')->middleware('api')->group(function () {
    // 图片验证码
    Route::get('captcha', [\App\Foundation\Infra\Captcha\Controllers\Common\CaptchaController::class, 'index']);
    // 查询地区列表
    Route::get('region', [\App\Foundation\Infra\Region\Controllers\Common\RegionController::class, 'index']);
});
// end
