<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Api\Common\Controllers\AgreementController;
use App\Api\Common\Controllers\AuthController;
use App\Api\Common\Controllers\CaptchaController;
use App\Api\Common\Controllers\ConfigController;
use App\Api\Common\Controllers\DictionaryController;
use App\Api\Common\Controllers\LogisticsCallbackController;
use App\Api\Common\Controllers\NoticeController;
use App\Api\Common\Controllers\PaymentCallbackController;
use App\Api\Common\Controllers\RegionController;
use App\Api\Common\Controllers\SmsController;
use App\Api\Common\Controllers\UploadController;
use Illuminate\Support\Facades\Route;

// 协议详情
Route::get('agreements/{id}', [AgreementController::class, 'show'])->name('agreements.{id}');
// 最新协议
Route::get('latest', [AgreementController::class, 'latest'])->name('latest');
// 刷新 Token
Route::post('v1/auth/refresh', [AuthController::class, 'refresh']);
// 显示图片验证码
Route::get('captcha', [CaptchaController::class, 'index'])->name('captcha');
// 配置列表
Route::get('configs', [ConfigController::class, 'index'])->name('configs');
// 配置详情
Route::get('configs/{id}', [ConfigController::class, 'show'])->name('configs.{id}');
// 字典列表
Route::get('dictionaries', [DictionaryController::class, 'index'])->name('dictionaries');
// 字典详情
Route::get('dictionaries/{id}', [DictionaryController::class, 'show'])->name('dictionaries.{id}');
// 快递回调通知
Route::post('kuaidi/notify', [LogisticsCallbackController::class, 'kuaidiNotify']);
// 公告列表
Route::get('notices', [NoticeController::class, 'index'])->name('notices');
// 公告详情
Route::get('notices/{id}', [NoticeController::class, 'show'])->name('notices.{id}');
// 支付宝支付回调
Route::post('alipay/notify', [PaymentCallbackController::class, 'alipayNotify']);
// 微信支付回调
Route::post('wechat/notify', [PaymentCallbackController::class, 'wechatNotify']);
// 银联支付回调
Route::post('unionpay/notify', [PaymentCallbackController::class, 'unionpayNotify']);
// 地区列表
Route::get('regions', [RegionController::class, 'index'])->name('regions');
// 地区子级列表
Route::get('{id}/children', [RegionController::class, 'children'])->name('{id}.children');
// 发送短信验证码
Route::post('sms/code', [SmsController::class, 'code']);
// 图片上传
Route::post('image', [UploadController::class, 'image']);
// 文件上传
Route::post('file', [UploadController::class, 'file']);
// OSS上传策略
Route::post('oss-policy', [UploadController::class, 'ossPolicy']);
