<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询搜索引擎列表接口
Route::post('searchEngine/query', [\App\Bundles\Search\Controllers\SearchEngineController::class, 'query']);
// 新增搜索引擎接口
Route::post('searchEngine/store', [\App\Bundles\Search\Controllers\SearchEngineController::class, 'store']);
// 获取搜索引擎详情接口
Route::get('searchEngine/show', [\App\Bundles\Search\Controllers\SearchEngineController::class, 'show'])->name('searchEngine.show');
// 更新搜索引擎接口
Route::put('searchEngine/update', [\App\Bundles\Search\Controllers\SearchEngineController::class, 'update']);
// 删除搜索引擎接口
Route::delete('searchEngine/destroy', [\App\Bundles\Search\Controllers\SearchEngineController::class, 'destroy']);
// 查询搜索关键词列表接口
Route::post('searchKeywords/query', [\App\Bundles\Search\Controllers\SearchKeywordsController::class, 'query']);
// 新增搜索关键词接口
Route::post('searchKeywords/store', [\App\Bundles\Search\Controllers\SearchKeywordsController::class, 'store']);
// 获取搜索关键词详情接口
Route::get('searchKeywords/show', [\App\Bundles\Search\Controllers\SearchKeywordsController::class, 'show'])->name('searchKeywords.show');
// 更新搜索关键词接口
Route::put('searchKeywords/update', [\App\Bundles\Search\Controllers\SearchKeywordsController::class, 'update']);
// 删除搜索关键词接口
Route::delete('searchKeywords/destroy', [\App\Bundles\Search\Controllers\SearchKeywordsController::class, 'destroy']);
