<?php

// ==========================================================================
// Code generated by gen:route:web CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

Route::any('activity.php', [App\Modules\Web\Controllers\ActivityController::class, 'index'])->name('activity');
Route::any('affiche.php', [App\Modules\Web\Controllers\AfficheController::class, 'index'])->name('affiche');
Route::any('affiliate.php', [App\Modules\Web\Controllers\AffiliateController::class, 'index'])->name('affiliate');
Route::any('article_cat.php', [App\Modules\Web\Controllers\ArticleCatController::class, 'index'])->name('article_cat');
Route::any('article.php', [App\Modules\Web\Controllers\ArticleController::class, 'index'])->name('article');
Route::any('auction.php', [App\Modules\Web\Controllers\AuctionController::class, 'index'])->name('auction');
Route::any('brand.php', [App\Modules\Web\Controllers\BrandController::class, 'index'])->name('brand');
Route::any('captcha.php', [App\Modules\Web\Controllers\CaptchaController::class, 'index'])->name('captcha');
Route::any('catalog.php', [App\Modules\Web\Controllers\CatalogController::class, 'index'])->name('catalog');
Route::any('category.php', [App\Modules\Web\Controllers\CategoryController::class, 'index'])->name('category');
Route::any('comment.php', [App\Modules\Web\Controllers\CommentController::class, 'index'])->name('comment');
Route::any('compare.php', [App\Modules\Web\Controllers\CompareController::class, 'index'])->name('compare');
Route::any('exchange.php', [App\Modules\Web\Controllers\ExchangeController::class, 'index'])->name('exchange');
Route::any('feed.php', [App\Modules\Web\Controllers\FeedController::class, 'index'])->name('feed');
Route::any('flow.php', [App\Modules\Web\Controllers\FlowController::class, 'index'])->name('flow');
Route::any('gallery.php', [App\Modules\Web\Controllers\GalleryController::class, 'index'])->name('gallery');
Route::any('goods.php', [App\Modules\Web\Controllers\GoodsController::class, 'index'])->name('goods');
Route::any('group_buy.php', [App\Modules\Web\Controllers\GroupBuyController::class, 'index'])->name('group_buy');
Route::any('index.php', [App\Modules\Web\Controllers\IndexController::class, 'index'])->name('index');
Route::any('message.php', [App\Modules\Web\Controllers\MessageController::class, 'index'])->name('message');
Route::any('myship.php', [App\Modules\Web\Controllers\MyshipController::class, 'index'])->name('myship');
Route::any('package.php', [App\Modules\Web\Controllers\PackageController::class, 'index'])->name('package');
Route::any('pick_out.php', [App\Modules\Web\Controllers\PickOutController::class, 'index'])->name('pick_out');
Route::any('quotation.php', [App\Modules\Web\Controllers\QuotationController::class, 'index'])->name('quotation');
Route::any('receive.php', [App\Modules\Web\Controllers\ReceiveController::class, 'index'])->name('receive');
Route::any('region.php', [App\Modules\Web\Controllers\RegionController::class, 'index'])->name('region');
Route::any('respond.php', [App\Modules\Web\Controllers\RespondController::class, 'index'])->name('respond');
Route::any('search.php', [App\Modules\Web\Controllers\SearchController::class, 'index'])->name('search');
Route::any('sitemap.php', [App\Modules\Web\Controllers\SitemapController::class, 'index'])->name('sitemap');
Route::any('snatch.php', [App\Modules\Web\Controllers\SnatchController::class, 'index'])->name('snatch');
Route::any('tag_cloud.php', [App\Modules\Web\Controllers\TagCloudController::class, 'index'])->name('tag_cloud');
Route::any('topic.php', [App\Modules\Web\Controllers\TopicController::class, 'index'])->name('topic');
Route::any('vote.php', [App\Modules\Web\Controllers\VoteController::class, 'index'])->name('vote');
Route::any('wholesale.php', [App\Modules\Web\Controllers\WholesaleController::class, 'index'])->name('wholesale');
