<?php

declare(strict_types=1);

namespace App\Modules\Admin\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Str;

class GenRouteCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'gen:route:admin';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate admin routes';

    private array $ignoreControllers = [
        'BaseController',
    ];

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $routeContent = '';
        $files = glob(dirname(__DIR__).'/Controllers/*Controller.php');
        foreach ($files as $file) {
            $controller = basename($file, '.php');
            if (in_array($controller, $this->ignoreControllers)) {
                continue;
            }
            $name = Str::snake(Str::substr($controller, 0, -10));
            $controller = 'App\\Modules\\Admin\\Controllers\\'.$controller.'::class';
            $routeContent .= "\nRoute::any('$name.php', [$controller, 'index'])->name('$name');";
        }
        file_put_contents(dirname(__DIR__).'/Routes/admin.gen.php', $this->getRouteContent($routeContent));
        $this->info('ok');
    }

    private function getRouteContent(string $routeContent): string
    {
        return '<?php

// ==========================================================================
// Code generated by gen:route:admin CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;
'.$routeContent;
    }
}
