<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Domains\Product\Controllers\ProductCategoryController;
use App\Domains\Product\Controllers\ProductController;
use App\Domains\Product\Controllers\ProductReviewController;
use App\Domains\Product\Controllers\ProductSkuController;
use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('productCategory/search', [ProductCategoryController::class, 'search']);
// 新增接口
Route::post('productCategory/store', [ProductCategoryController::class, 'store']);
// 获取详情接口
Route::get('productCategory/show', [ProductCategoryController::class, 'show'])->name('productCategory.show');
// 更新接口
Route::put('productCategory/update', [ProductCategoryController::class, 'update']);
// 删除接口
Route::post('productCategory/destroy', [ProductCategoryController::class, 'destroy']);
// 查询列表接口
Route::post('product/search', [ProductController::class, 'search']);
// 新增接口
Route::post('product/store', [ProductController::class, 'store']);
// 获取详情接口
Route::get('product/show', [ProductController::class, 'show'])->name('product.show');
// 更新接口
Route::put('product/update', [ProductController::class, 'update']);
// 删除接口
Route::post('product/destroy', [ProductController::class, 'destroy']);
// 查询列表接口
Route::post('productReview/search', [ProductReviewController::class, 'search']);
// 新增接口
Route::post('productReview/store', [ProductReviewController::class, 'store']);
// 获取详情接口
Route::get('productReview/show', [ProductReviewController::class, 'show'])->name('productReview.show');
// 更新接口
Route::put('productReview/update', [ProductReviewController::class, 'update']);
// 删除接口
Route::post('productReview/destroy', [ProductReviewController::class, 'destroy']);
// 查询列表接口
Route::post('productSku/search', [ProductSkuController::class, 'search']);
// 新增接口
Route::post('productSku/store', [ProductSkuController::class, 'store']);
// 获取详情接口
Route::get('productSku/show', [ProductSkuController::class, 'show'])->name('productSku.show');
// 更新接口
Route::put('productSku/update', [ProductSkuController::class, 'update']);
// 删除接口
Route::post('productSku/destroy', [ProductSkuController::class, 'destroy']);
