openapi: 3.0.0
info:
  title: API文档
  description: 门户平台接口
  contact:
    name: 'API Develop Team'
  version: '1.0'
servers:
  -
    url: 'http://127.0.0.1:8000'
    description: 开发环境
  -
    url: 'https://demo.phpmall.net'
    description: 测试环境
paths:
  /catalog:
    get:
      tags:
        - 类目
      summary: 全部类目
      operationId: 482f0565a9ee87709ed175399a19769e
      responses:
        '200':
          description: OK
  /category:
    get:
      tags:
        - 商品分类
      summary: 商品分类
      operationId: 27d51922c466fe54058ea23487ee987b
      responses:
        '200':
          description: OK
  /:
    get:
      tags:
        - 首页
      summary: 商城首页
      operationId: 30dfd0c1f8ba31d1255c25abb4be470a
      responses:
        '200':
          description: OK
